### ISSUE TITLE
Nyx' carapace is not procced by Techies proximity mines

### ISSUE THREAD

**Issue by Seafarm** [ValveSoftware/Dota2-Gameplay#10100]
### Ability name

Spiked carapace

### Description

Techies ultimate ability 'Proximity mines' does not trigger Spiked Carapace, i.e. Nyx takes full damage and Techies is neither stunned nor takes damage, when spiked carapace is active and a mine is triggered.

### Example Match ID (and possibly Timestamp)

7242375177

**Comment by TheZett** [comment]
This is intended.

Spiked Carapace only works against heroes and the Proximity Mine is its own damage source, which is why its damage cannot be blocked & reflected. Basically the same interaction as Witch Doctor's Death Ward.

Meanwhile the Sticky Bomb is not its own damage source, its damage is sourced to Techies, and thus Sticky Bomb can be blocked and reflected.

**Comment by Seafarm** [comment]
Thank you for clarifying :)
