### ISSUE TITLE
Quick attack does not work on hero portraits

### ISSUE THREAD

**Issue by gmackall** [ValveSoftware/Dota2-Gameplay#10275]
### Description

The attack command interacts with the hero portraits at the top of the screen differently depending on your quick attack setting.

With it enabled, your hero performs an attack command at the location "behind" the hero portrait (as if the portraits weren't there, and you had clicked on the ground).

With it disabled, your hero performs an attack command targeted on the hero that corresponds to the portrait you clicked on.

This is somewhat important, as it means players can pull creep aggro without moving their screen with the option disabled, but not with it enabled.

**Comment by voddov** [comment]
Bump up, as a quick attack user, i found this is annoying af too.

**Comment by Joyfulbeekeeper** [comment]
Still not fixed...
Valve, please!

**Comment by zeljko1999** [comment]
Please fix, this is so annoying!!

**Comment by qweqwsxz** [comment]
yes please ! these 2 attack modes should be the same

**Comment by Mhd-Adel** [comment]
Please fix this issue , pleaseeee

**Comment by haggers345** [comment]
Are you preparing to relocate a long way, from the charming streets of San Francisco to the energetic metropolis of Dallas? Top Moving Company is the only company you need to consider if you want a smooth and stress-free move. Our knowledgeable staff specializes in moving people from San Francisco to Dallas and offers a wide selection of services to suit your requirements. We manage every step of your relocation with accuracy and care, from packing and loading through transportation and unloading. You may concentrate on the thrill of your new Dallas experience while Top Moving Company is taking care of your possessions, so you can enjoy it more. Your move from the Bay Area to the Lone Star State will go smoothly because to our dedication to quality.

**Comment by jeffhill** [comment]
This should be fixed in the next client update we ship (not the one we just shipped today).

Thanks for the bug report and the very clear description!

**Comment by supermikes** [comment]
> This should be fixed in the next client update we ship (not the one we just shipped today).
> 
> Thanks for the bug report and the very clear description!

Hey Jeff, 

It seems the bug wasn't fixed in today's patch. Can you please check in on this when you get a chance?

**Comment by voddov** [comment]
It was not fixed, the patch note was wrong. Sadge

**Comment by gmackall** [comment]
Confirmed it as fixed in game. Thanks!
