### ISSUE TITLE
Player view no longer functions in DotaTV

### ISSUE THREAD

**Issue by BenLubar** [ValveSoftware/Dota2-Gameplay#11026]
### Description

1. Spectate any live match
2. Set the camera mode to "player view"
3. The camera is showing the middle of the river and no mouse cursor

**Comment by specurial** [comment]
same problem

**Comment by muciflex** [comment]
How long does it take to fix issues , this is my first time reporting an issue/bug for DOTA2 ?
It really makes learning very limited since I need to see player perspective to understand some actions/decisions/moves. 
Thank you.

**Comment by BenLubar** [comment]
Depends how hard it is to figure out why it's happening. Generally, once whoever's fixing the bug figures out why it's happening it can be fixed in a matter of seconds.

**Comment by shaileshgarg** [comment]
Seems to be working after today's update

**Comment by mayurrr98** [comment]
> Seems to be working after today's update

Still see the same issue. Is it really working for you?

**Comment by ajaykauthale1** [comment]
Still having the issue any update on this

**Comment by NoPhaseNoKill** [comment]
So I've been experiencing random issues like this with switching the view for probably about 2/3 years. It keeps rearing it's head in multiple subtle ways- and I'd finally had enough of it to come searching and stumbeld across this thread (seems pretty popular from 3 days ago).

The specific example listed in this issue is related to 'Player View' - but to my knowledge this specific bug has existed in many subtle forms, often with a moving target (aka changing behaviour depending on the implementation of code).


## What I believe to be the cause/determining factor for this issue:

> The user has PREVIOUSLY 'watched' a game.

I say watched with airquotes because this and other bugs I've noticed in the past also happen for replays. This means the bug is in an area which both replays and 'live games' use (common, but may help the dev pinpoint the issue depending on what the code looks like).

The reason as to why this bug has existed in many forms over the years, may also be linked to the fact that you have to have previous state, and depending on the implementation of tests, they may not load 'previously watched games settings' to enable/catch these edge cases.

## Steps to replicate issue:

1. Ensure you have previously 'watched a game'
2. Open a live game from the watch tab
3. Select the 'Player View' from the dropdown

## Subtlties/oddities noticed:

1. Use the above steps to replicate issue. Select something new from the dropdown ('Hero Case' for example). The playback control panel now displays TWO different things. The top section displays 'Player View', while the bottom section displays 'Hero Chase'. Now if you go to the dropdown againand select 'Player View', it displays the INVERSE of what we had before ('Hero Chase' at top section, 'Player View' at bottom section). No matter which you select from the dropdown, it will switch these as showcased above. It appears to be using an index/switching them, and will mean that they are always 'out of sync'. 

2. Getting them back 'in sync' can ONLY be achieved by selecting 'Directed Camera' and overriding the camera, and waiting for it take control again

3. Regardless of in or out of sync, no matter which what you try (and trust me, I've tried all variations I can think of), this is an irrecoverable bug in that the user cannot ever get the desired behaviour (watching a players view/perspective)

## Where the issue most likely lies/what it's related to:

### Terminology: 

Mappings: This refers to the mapping of an item in the dropdown, and what it's action should be.

Example: The 'Player View' mapping means that when it is selected, the 'automated camera type' should result in the action taken of using the player view automated camera. Subsequently, if I select 'Directed Camera', it should use an AI algo (or whatever implementation you have) to determine how to follow along and move the camera

As I'm a developer myself, it's almost certainly an issue with arrays/lists/indexes, just by the specific type of behaviour we're seeing. The fact that the selections and UI can become 'out of sync' (explained in the subtlties/oddities section), to me indicates one of two things.


1. The mappings being shown in the UI are not what is actually selected/being used in the state. ie it's using the last index (or old value) - but in this case I would have expected then switching the 'camera type' to have resolved it, or;

2. The mappings it is using in the state are incorrect/misconfigured for the current 'structure'. For example: Let's say the mappings used to have a key which was used as a part of an index. The key was 'Player Perspective' (an example of what it used to be from memory). Because that key no longer exists, and the index is being used to link from the camera type -> action needing to be taken, it can't the fact that it needs to set the 'automated camera type' to the 'player view automated camera'. This is what I suspect is the root cause
3. Previous settings are loaded, which 'override' the defined mappings, and cause havoc around indexes (perks of legacy code bases/settings/configs hehe)

## Key gotchas/test scenarios that SHOULD be covered after applying your fix:

This same issue I have seen in this 'replay panel' about 5-10 times over 7/8 years. These are obviously generic assumptions I'm making, but there is some fundamental test coverage you're missing around this panel and it SHOULD be addressed. Otherwise, everytime changes are made, this issue, or a variant of it, is going to keep cropping up.

1. When the camera types/mappings change over time (which becomes more prevalent in older code bases, and is what I suspect has happened here/before for other bugs I've noticed), you need to ensure that invalid mappings/indexes are 'discovered' and result in a default behaviour. The difficult part about this is that there is not always a one to one mapping (for old -> new values). In the case of "Player Perspective" being updated to 'Player View' this may have been relatively simple. But what happens when there aren't any overlapping words or the overlapping words are contained within multiple mapping entries?

2. You need a way of programatically writing your tests so that it not only caters for the mapping edge cases (valid/invalid ones), but also the fact that loading the previous 'state' DOES NOT in any way, shape or form override your mappings. This is a very important subtly. 

Take the following example:
1. Someone updates the mappings/key/action
2. Patch is released
3. People go to load to patch, but have old 'settings/config'
4. It looks like the default behaviour attempts to use some old/incorrect mapping, with no effect.
5. Instead, you should have 'compatible' mapping versions, whereby if the mapping it's looking at doesn't match the mapping version being loaded, you can 'invalidate the cache/saved state/config', fully reload it using the new ones, and allow users to then use them


Please note: @jeffhill or any other dev, these are obviously making a lot of assumptions, because I can't see your codebase. If you require any further information from me, please feel free to reach out and I'll be more than happy to help. This is one of the most ANNOYING bugs in dota2 of all time (one of it's many variants), and I wanted to try and provide as much context (with the knowledge of both dota + as a software developer) so that we can try and get rid of all of the possible variants of this bug once and for all.

 
PS: Absolutely love what you've done with the game over many years, and is a big reason for why I spent so long trying to track this issue down. Thank everyone on the team for me. The community may not say it much, but we love the work y'all do :)

**Comment by shaileshgarg** [comment]
> > Seems to be working after today's update
> 
> Still see the same issue. Is it really working for you?

Tested again, on Live matches it doesn't work, on Replays it is working.

**Comment by shaileshgarg** [comment]
Today when I was checking a friend's live match, there player view was working, but switching to a match with more viewers it breaks.

**Comment by muciflex** [comment]
Doest anybody ever going to look over this , I haven't opened dota in like a week . I know I do not matter in the scale of player volume but already there are some people complaining about this issue.

**Comment by muhusni** [comment]
When I watch my friend's game, the player view works. But when I watch pro dota pub, it doesnt.

**Comment by robert-gogolan** [comment]
After update 7.34c (9/8/2023) this issue is still present.

Places where player view is working: Replays, Watch friend
Places where player view is not working: Live games, Watch friend live (dota plus feature)

**Comment by aparatrepresji** [comment]
I've noticed that is some games it works for just one team, and in others (most of them) it doesnt work in both.

**Comment by robert-gogolan** [comment]
After last night update, the watch game feature is no longer working at all.
It just remain stuck with this popup.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/13692333/dc0adf7d-50d5-4831-ade8-76586a871cd2)

Might be related to https://github.com/ValveSoftware/Dota2-Gameplay/issues/11837

**Comment by NoPhaseNoKill** [comment]
As an FYI, you don't need to continually spam/pollute the thread reiterating the same problem. 

These threads exist for:
1) thumbs up if you're having the same problem to gauge numbers
2) additional information provided on this specific issue
3) confirmation between devs/community that an issue is fixed and can be closed

The problem is still open, which indicates it's still being worked on. If it gets closed, and the problem is still not fixed, that is when you would update with something like 'issue still exists and this thread needs to be re-opened ...etc'

**Comment by gnihton-boi** [comment]
I don't know it any Valve dev will read this but I've figure out that this problem seems to only happen on games with spectator chat on, if you spectate a game with the chat on then player view is non-functional and if you watch one with no viewers (and no chat) then it works fine.

**Comment by fatoskurtishi** [comment]
> I don't know if any Valve dev will read this but I've noticed that this problem seems to only happen on games with spectator chat on, if you spectate a game with the chat on then player view is non-functional and if you watch one with no viewers (and no chat) then it works fine.
> 
> Edit: I just realised that you seem to connect to spectator chat even when you're the only viewer, so it's if you're the first/only viewer instead 😛

Just tested Player View while 0 spectators it works. but if there is 1+ spectators it doesn't work.

**Comment by krtek2k** [comment]
even the stupidiest fanatics for this shitgame now can see that they dont give damn :-D
yes if you are first spectator you can enjoy the playerview, neat

**Comment by jeffhill** [comment]
Player perspective in Live games should be fixed now with the server update that was just shipped. This was a deep one to track down folks, thanks for all the reports!

**Comment by shaileshgarg** [comment]
> Player perspective in Live games should be fixed now with the server update that was just shipped. This was a deep one to track down folks, thanks for all the reports!

So can we expect a blog post for this one.

**Comment by NoPhaseNoKill** [comment]
> > Player perspective in Live games should be fixed now with the server update that was just shipped. This was a deep one to track down folks, thanks for all the reports!
> 
> So can we expect a blog post for this one.

Lmao I was thinking the exact same thing!

@jeffhill FYI I've been seeing this issue fixed for the last ~2 days. Do you guys release these changes to low population servers first to test changes? I'm from Australia so am just curious as to why I was seeing the changes before you posted/before the actual update appeared to come out.

Regarding the issue: as far as I'm concerned, this issue can be closed. @BenLubar , @robert-gogolan , @gnihton-boi are you all seeing that this is now fixed?

**Comment by BenLubar** [comment]
Yep, looks like it's fixed from my perspective. Or I guess not-my perspective.

Looking forward to the Between The Lanes on this one (if it's coming).

**Comment by robert-gogolan** [comment]
Issue is fixed, all the duplicates should be closed as well, i know i closed mine some time ago.

**Comment by alexscott64** [comment]
Issue is now back on the newest patch. Previously the issue would go away after some time, but now anyone in the game that isn't who you selected for "Watch Friend Live" (even if they are your friend) has the camera bug.

**Comment by NoPhaseNoKill** [comment]
I'm also getting the same issue again.

**Comment by Omga4000** [comment]
> Issue is now back on the newest patch. Previously the issue would go away after some time, but now anyone in the game that isn't who you selected for "Watch Friend Live" (even if they are your friend) has the camera bug.

Same here. Only the player that was selected when I pressed "Watch Friend Live" has a working player view camera.
Rest of the players are bugged.
