### ISSUE TITLE
death ward interacts with the ghost form as if it deals physical damage

### ISSUE THREAD

**Issue by Aradionov366** [ValveSoftware/Dota2-Gameplay#11489]
### Ability name

Death ward

### Description

title speaks for itself, death ward ignoring entities in ghost form, though it now deals pure damage instead of physical

### Example Match ID (and possibly Timestamp)

test in lobby

**Comment by LokeLok** [comment]
Intended. 

You can't attack people in ghost form and since Death Ward is attacking it will not work(damage type doesn't matter in this case). If you read the description of Ghost Shroud(Necrophose) or Decrepify(Pugna) it is stated on those however, on Ghost Scepter and Ethereal Blade the description is not good enough to explain this. You should close this post and make a new post asking for the description of these two Items to be updated.
