### ISSUE TITLE
Juggernaut is able to use Blade Fury while being affect by Shackles from Shadow Shaman

### ISSUE THREAD

**Issue by MenOfWar** [ValveSoftware/Dota2-Gameplay#11789]
### Ability name

Shackles

### Description

Juggernaut is able to use Blade Fury while being affect by Shackles from Shadow Shaman

Clip: https://youtu.be/xhd545mybow
Combat log: https://imgur.com/a/lIFeJHJ
Demo test: https://imgur.com/a/jTLzcil

### Example Match ID (and possibly Timestamp)

7329251650 27:20

**Comment by KazsaB** [comment]
Not a bug, shaman stopped the channel which canceled the shackle and allowed Jugg to Blade Fury.  Check Players view and not hero chase to see.

**Comment by arkydon** [comment]
> Not a bug, shaman stopped the channel which canceled the shackle and allowed Jugg to Blade Fury.  Check Players view and not hero chase to see.

Are you sure. He says in the reddit thread it happened multiple times in that game. Plus its happened to other people too (Gorgc), defiant shell seems to be the problem.

**Comment by KazsaB** [comment]
> > Not a bug, shaman stopped the channel which canceled the shackle and allowed Jugg to Blade Fury.  Check Players view and not hero chase to see.
> 
> Are you sure. He says in the reddit thread it happened multiple times in that game. Plus its happened to other people too (Gorgc), defiant shell seems to be the problem.
> 
> Also check his demo test.

So far with all the evidence I am pretty confident there is no bug regarding using debuff immunity during shackles.  The Gorgc one I checked and Gorgc used bkb just before shackles was cast.  I have already checked this one and it is clear that Shaman issued a move command after shackles.  His demo test was unable to recreate the scenario because you simply just can not, I have also tried.  The only bug is that he is able to hit a Shaman's ward during a stun with defiant shell.
