### ISSUE TITLE
Freezing the whole game with the help of Lone Druid and his bear.

### ISSUE THREAD

**Issue by gh215** [ValveSoftware/Dota2-Gameplay#11830]
### Item name

Iron Branch

### Description

If you completely fill the slots of spirit-bear with Iron Branches, then buy 2 more Branches that will lay in the stash and move 
second Branch to any slot in the stash, the whole game will freeze, but does not crash and can only hear the background of the game. I have to close the game with the help of task manager.

UPD: I have the fans running at max right now, even though the game has been out for a while.

![20230911223716_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/52608180/936a0810-c85c-41e7-960f-0bcf77a1877d)

### Example Match ID and Timestamp

You can try it in lobby. No difference

**Comment by eric1294** [comment]
Why would the fans be going at max?

Also just tried this in the demo hero area and yes I can confirm that this happens. Why does Lone Druid have to be such a risky hero to play without **crashing** the game?!

**Comment by rianrain** [comment]
Bug abuse for 8 hours and no hero disable or patch cool

**Comment by KazsaB** [comment]
Happens with any item, most likely due to bear not supposed to have a stash and then moving an item causes some interaction that cant compute which crashes the game.  I haven't played LD in a while though so I do not know if bear is supposed to have a separate stash at least or if it should be shared.  Items in bear stash can only be sold or combination locked.  If you try to move an item into stash from bear it will not work, same if you drop an item and try.  Courier is also unable to take from bear stash.  This could be due to the patch that made bear a creep-hero resulting in it receiving its own stash.

**Comment by TobyFlendersonFromHR** [comment]
neat trick, gonna use it to climb some rank, cheers

**Comment by gh215** [comment]
Big fixed
