### ISSUE TITLE
GUI ERROR

### ISSUE THREAD

**Issue by dekconcat** [ValveSoftware/Dota2-Gameplay#12084]
### Description

Some stats now show in mini GUI. PLS fix this.

### Screenshots

![Screenshot_2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/98456429/597f0a06-8ce7-4319-813b-25e1393d41e9)

**Comment by SpiritWinD86** [comment]
it's not even an error or a bug. close the issue and check in the game settings "Unit query overrides hero control console".

**Comment by dekconcat** [comment]
> it's not even an error or a bug. close the issue and check in the game settings "Unit query overrides hero control console

that mini hub not showing hero stats, i try on a larger moniter but still the same.
is there anyway to fix that ?

**Comment by SpiritWinD86** [comment]
> > 
> 
> that mini hub not showing hero stats. I also tried on a larger monitor but still the same. is there anyway to fix that ? edit: it's not showing neutrals items and tp scroll too. (sry for my bad english)

oh, ok. i thought you were trying to get rid of that panel. 

anyway the devs actually stopped maintaining this feature like a year ago or so.

> jeffhill commented [on Jun 23, 2022](https://github.com/ValveSoftware/Dota2-Gameplay/issues/333#issuecomment-1163608484)
BLUF: We're not maintaining this panel and we are planning to remove it after TI this year.
Thank you for taking the time to report these bugs and thank you to everyone who upvoted the issue! This issue led to a broader discussion this morning in the Dota developers chat about what to do about this issue - but we still don't plan to support this feature long term. This panel was a neat idea we tried in the UI redesign some years ago and while it was kind of interesting, in practice very few players actually used the panel even when it was new. Since we're going to remove this panel in a few months time, and so few players are using it today, it doesn't make a lot of sense to spend the time fixing these bugs with it.

**Comment by dekconcat** [comment]
> > > 
> > 
> > 
> > that mini hub not showing hero stats. I also tried on a larger monitor but still the same. is there anyway to fix that ? edit: it's not showing neutrals items and tp scroll too. (sry for my bad english)
> 
> oh, ok. i thought you were trying to get rid of that panel.
> 
> anyway the devs actually stopped maintaining this feature like a year ago or so.
> 
> > jeffhill commented [on Jun 23, 2022](https://github.com/ValveSoftware/Dota2-Gameplay/issues/333#issuecomment-1163608484)
> > BLUF: We're not maintaining this panel and we are planning to remove it after TI this year.
> > Thank you for taking the time to report these bugs and thank you to everyone who upvoted the issue! This issue led to a broader discussion this morning in the Dota developers chat about what to do about this issue - but we still don't plan to support this feature long term. This panel was a neat idea we tried in the UI redesign some years ago and while it was kind of interesting, in practice very few players actually used the panel even when it was new. Since we're going to remove this panel in a few months time, and so few players are using it today, it doesn't make a lot of sense to spend the time fixing these bugs with it.

TKS
