### ISSUE TITLE
Dark Willow still being able to right click while bushwack stunned during shadow realm

### ISSUE THREAD

**Issue by centarcher** [ValveSoftware/Dota2-Gameplay#12458]
### Ability name

Shadow Realm + Bushwack

### Description

In a turbo game, Dark Willow used Shadow Realm and right clicked Slark, and then was stunned by Hoodwink Bushwack. She was dragged to the tree but was not fully stunned and still was able to attack (possibly use abilities and items as well), leading to Slark's death. This could be potentially game ruining if it happened in high level play.

### Example Match ID (and possibly Timestamp)

7362723239 (9:45 - 9:50)

video of bug: https://imgur.com/a/ILi8DeT
shows dark willow getting dragged to the tree, and even briefly given the bushwack debuff, but it is instantly removed and she is not stunned despite no strong dispels being used and the tree she is dragged towards is not destroyed.

**Comment by yckmm** [comment]
Bushwack doesn't hit on invisible units (Dark Willow is considered invisible during Shadow Realm).

**Comment by centarcher** [comment]
> Bushwack doesn't hit on invisible units (Dark Willow is considered invisible during Shadow Realm).

this is easily disproven in practice, you can try it yourself. she is not invisible and still gets stunned normally as she did in every other interaction during the same game.

https://imgur.com/a/ZKz3eFm

**Comment by yckmm** [comment]
Well, Bushwack definitely didn't work on Shadow Realm until recently. That's an undocumented (and maybe unintended) change.

**Comment by centarcher** [comment]
interestingly i just looked through her changelogs and found that in may 2023 they apparently "fixed" abilities affecting her in shadow realm as if she wasnt invisible. implying she should be considered invisible like you said, which means that this post is the intended effect and what happens regularly is the bug?

**Comment by commentator24** [comment]
there was a related update recently but im not sure what that does
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/e8c030a7-4c94-45e8-baba-71005e0a5be0)
is shadow realm is meant to behave the same as slark shadow dance?
in demo bushwack does not stun slark shadow dance while it stun dark willow shadow realm. inconsistent.
i think the actual bug is DW still hit by bushwack during shadowrealm. they're both shadow arent they?
someone made #7077 list maybe should be compared to slark shadow dance.

another bug is when bushwack is perhaps considered as a leash, or based on leash.
e.g. forcestaff ends any leash early, hence bushwack stun ends early too.
this means if slark leash duration is 0.5 sec left, a bushwack will end early too, and will not last 2 seconds, just 0.5 sec.
thats what happened in the video. slark leash was nearly over so willow wakes up early too
here's a demo that shows leash triggers bushwack to end early.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/5d0874f6-fdca-4642-9cb6-a8069b2a5d97)

**Comment by centarcher** [comment]
this is incredibly interesting, thank you very much for your insight to this. 
i think you're entirely correct with the bug being dark willow being able to be hit by bushwack at all during shadow realm, and thank you for adding this thread to the list. 
also that pounce/bushwack interaction bug is incredibly interesting and makes a lot of sense with how the game treats abilities.
