### ISSUE TITLE
CANT DOWNLOAD THE GAME

### ISSUE THREAD

**Issue by Aryel-Alves** [ValveSoftware/Dota2-Gameplay#12595]
### Description

Basicle im trying to download the game for more than one week and having the same problem, I deleted dota 2 from my pc and im trying to download again but the download dont pass de 15% mark stays in that way until it stops and display a network error message, i already tryed alot of things and nothing worked plz help me

List of things i tryed:
- Formated the desktop and updated windows to 11
- updated bios
- changed dns
- changed steam download server
- changed steam beta option
- removed the downloading folder of steam

### Screenshots

![Captura de tela 2023-10-05 071530](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47902117/b7c6f080-ce92-4fd9-ae1a-81186e0baa4c)
![Captura de tela 2023-10-05 071747](https://github.com/ValveSoftware/Dota2-Gameplay/assets/47902117/ef909718-5760-407c-902d-97abcddd0d43)

**Comment by lord8266** [comment]
Change your download region

**Comment by lord8266** [comment]
> changed steam download server
Try multiple different servers

**Comment by commentator24** [comment]
please screenshot your available space... maybe you don't have enough free space on that drive?

sometimes your storage drive has limitations on the maximum file size or number of files that can be stored in a single directory. e.g. max file size supported by FAT32 is 4 gigabytes (GB). so this means when you're nearly 4GB the dl will fail. you will need NTFS file system to support large download size

some ISP, antivirus, firewall, or download manager settings may block or stopping dl from completing. make sure you check 1 by 1 where the problem is

**Comment by Aryel-Alves** [comment]
Hi guys i tryed diferent servers and i have enough space on SDD, i dicover what was the problem was some configuration or ip blocked on my internet provider, a friend who lives in same street tryed to download and got the same issue, i used a VPN to download the game and worked.

ty for the help
