### ISSUE TITLE
Overwatch bug

### ISSUE THREAD

**Issue by JohnDope90** [ValveSoftware/Dota2-Gameplay#14118]
### Description

This is the second time I post about this problem with the new bahavior system! My first post is a month ago and nothing has happened. And you haven't heard from you, even though there have been numerous posts about the problem.

I played a ranked game: 7483000087 where I was a warlock. I did my best to win, I have the most hero dmg on our team, I have the most support contribution, and played my part. I didn't grief at any point in the game! My pos 1 and 2, would not play the game which is also evident from their dmg numbers, pos 1 wk: 13,665, pos 2 invoker: 17,556. I had as pos 5 warlock: 42,226.

We lost the game and immediately after the game I got an overwatch conviction for what? I also lost the behavior score and got a 4 hour timeout.

My communication score is 5.578 so it can't be because of that as I don't have the ability to communicate. It has been stuck on 5,578 for the last 5 summaries. ALSO A BUG!

Can we get some clear lines about the new system? I don't think my overwatch verdict was fair in any way! I just played the game and we lost. Assuming that the others have reported me therefore, how can these reporters go through? There can't possibly be anyone who has reviewed the game since I got the verdict right after the game ended!

Hope something happens soon, as it is impossible to get your behavior score and communication score back on track.

Added the specific match, sure that's the one it happened in. Since it was my second game and in the first I went 12-3-30 as a pos 5 warlock and we won. So it must be the specific game.

### Example Match ID (and possibly Timestamp)

7482948108

**Comment by JohnDope90** [comment]
#13330 - my previous post

**Comment by JohnDope90** [comment]
now im stucked in the most toxic single draft games! PLS FIX THIS BAHAVIOR SCORE! ITS NOT FAIR!!!!

**Comment by NAlexP** [comment]
Skynet is judge, jury and executioner. Post a picture of your incomming reports from that time to see if it was indeed overwatch or excessive reports. Google dota gdpr to see how.

**Comment by kevlg** [comment]
Some people got their score fixed 4 days ago, but they suddenly lost between 500 - 1000 points and yes somehow with comm deactivated you still could lose points

**Comment by peroni981** [comment]
i go another time in low prio for no reason, only because i take a decision to avoid my support because its low IQ player and go jungle min 6, farming and win a game at min 30 and they blame for this. game finish 15 2/top damage but when they game its finish i take 24 hours i cant play and low prio. No sense, when noob dont know what have to do in lane feeding and feeding like a retard. report you, i mean you report me when i carried a game 1vs 5 because you dont know to press button and if i ask you to do somenting you can say only ( shut up)

**Comment by NAlexP** [comment]
> i go another time in low prio for no reason, only because i take a decision to avoid my support because its low IQ player and go jungle min 6, farming and win a game at min 30 and they blame for this. game finish 15 2/top damage but when they game its finish i take 24 hours i cant play and low prio. No sense, when noob dont know what have to do in lane feeding and feeding like a retard. report you, i mean you report me when i carried a game 1vs 5 because you dont know to press button and if i ask you to do somenting you can say only ( shut up)

Jungling is griefing, though. But I get your vibe. When I see my team is garbage, I farm lanes by splitpushing and only show up at fights I am 100% certain I will win. Suffice to say, if the team is garbage, they won't understand this strategy and I end up with 4 reports on a won game, and low priority on a lost one with scores like this: https://www.dotabuff.com/matches/7485526322

**Comment by peroni981** [comment]
The problem is the behavior system is not working, I’m telling you that I have a low behavior despite playing well, I have the communication button disabled. yet I have the behavior of communications at 6500. if I can not write because I disabled the key how does the system to validate reports on communications. Valve is making big mistakes in giving unlimited reports, people with clear real-life lashes taking it out on a game. 
![20231214142523_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/141838670/46d957a6-055b-4df5-b131-7f8752229b12)
look, I set up 2 new accounts in the same way, because in my main account I have low behavior and I didn't understand why. so if I can't speak I repeat, why does the system validate the reports as true?
I actually ask who created this cute fake system, power to fools! no Valve control algorithm on the actual speaking or not.

**Comment by NAlexP** [comment]
> The problem is the behavior system is not working, I’m telling you that I have a low behavior despite playing well, I have the communication button disabled. yet I have the behavior of communications at 6500. if I can not write because I disabled the key how does the system to validate reports on communications. Valve is making big mistakes in giving unlimited reports, people with clear real-life lashes taking it out on a game. ![20231214142523_1](https://private-user-images.githubusercontent.com/141838670/290533126-46d957a6-055b-4df5-b131-7f8752229b12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjM2MTcsIm5iZiI6MTcwMjU2MzMxNywicGF0aCI6Ii8xNDE4Mzg2NzAvMjkwNTMzMTI2LTQ2ZDk1N2E2LTA1NWItNGRmNS1iMTMxLTdmODc1MjIyOWIxMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxNDE1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWZhZTZlNjhiMTk5YWZiOWNlNzQ4NTI1ZDQ4Mzg4ZDIyMjMxZmJjN2ZjOTBjYmU2MDUyYmUxYjgyNTBhZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4_6Zrm_sn4RdWBkcv-kdgFS1EKQCdVWmQ2cA4yGro4Q) look, I set up 2 new accounts in the same way, because in my main account I have low behavior and I didn't understand why. so if I can't speak I repeat, why does the system validate the reports as true? I actually ask who created this cute fake system, power to fools! no Valve control algorithm on the actual speaking or not.

No, I agree. There's something really fucked going on with coms score, and I also disable my coms key. Also, something really fucked with behaviour as well. It's insane, considering that when they released the update it was working perfectly and the games were super nice.

I suspect that the AI got trained on stupid data post release.

Still, I personally would report someone that jungles and isn't even pushing lanes while we fight 4v5.
