### ISSUE TITLE
QOL: Add surrender vote

### ISSUE THREAD

**Issue by sirgermund** [ValveSoftware/Dota2-Gameplay#1420]
### Description

I think we need a surrender vote as it done in CS:GO. I know that there is a possibility to win any game, but if 5 players don't see ways of doing it and just want to end game right now then surrender vote seems fair enough. There are many ways of doing it in the way so it will not be used by players just to show their feelings about the current game like make that vote possible only if there is a strong reason for that for example if enemy team has 10000 gold/exp more on 15 minute of a game. I think just the option to end the game like this without waiting 5-15 minutes to get the same result will have a positive effect on the players.

**Comment by hallsteinx** [comment]
If you don't want to play the game then don't queue for a match.

**Comment by geras256** [comment]
League of Legends sounds like the right game for you then.

**Comment by Daar543** [comment]
Not a QoL because there is no "workaround" how to make whole team instantly lose a match without side-effects.

**Comment by Daar543** [comment]
I would not mind using it in cases where "gg" can be used to finish a game.

**Comment by sirgermund** [comment]
I just wonder why there are so much dislikes on surrender ideas? This thing isn't something that affects everybody. If you think there is a chance to win, ok, no problem, you will continue to play. But if all 5 players decide to surrender then I don't see any problem. Anyway this surrender vote can be implemented to be used only if you play in stack of 5, that way there cannot be any problem at all.

**Comment by Aluerie** [comment]
*Here particularly* you get dislikes because it is not "QoL suggestion" in a development definition of it - it's a Full request feature. You can't just say QoL and ask devs to implement something this serious. This is not what the repository is for.

My life would be pretty High Quality if Battle Pass was free, if I could follow pro-players (like on twitch) and get notified when they start a pub game ; but I can't ask devs about it here.

If you really want to discuss this with people you should go on forums like reddit.

**Comment by kylegotchoo** [comment]
👎
