### ISSUE TITLE
Khanda damage doesn't apply if it would be lethal

### ISSUE THREAD

**Issue by edsca** [ValveSoftware/Dota2-Gameplay#14311]
### Item name

Khanda (Phylystalys)

### Description

The new item Khanda seems to not do the initial cast damage if the damage value exceeds the opponents current health.
In theory, a sufficiently duelled-up legion commander should be able to one-shot an enemy hero with just the initial burst damage.
However, when testing in lobby it seems this is not the case

To replicate, open demo mode with legion commander, get to level 30 and enable free spells. Give legion commander a Khanda and spawn a bunch of lvl 1 enemies. Now just go wild clicking duel, you'll notice that the amount of initial damage increases until the point where it would exceed the enemy's initial health. At this point the Khanda stops doing damage altogether.

Duel Damage = 722 nearly kills the geezer outright
![Duel Damage = 722 nearly kills the geezer outright](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29621056/b73f0dde-3144-452e-95e3-a37c38a0c81f)

...but win one more duel at your peril, you'll lose access to the spell that kills you instantly
![Duel Damage = 760 man don't care about all that](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29621056/0c905a98-bf3a-42b2-9b27-2fef49e0c288)

This probably isn't a realistic concern but please fix, i want to stack rapiers on aghs phylystalys sniper.

### Example Match ID and Timestamp

NA

**Comment by Ciantb** [comment]
i just tried this too but...
i think khanda won't do damage if the target HP below a certain % ( i think it is below 50% max HP )

**Comment by TeaTime93** [comment]
It's absolutely gamebreaking on Bounty Hunter, who gets a bonus from Jinada and could potentially snipe with it using track. Reported this one, too, so hope it gets fixed.

Best way to replicate this bug is get khanda and spam track. You'll see track never kills, or might if they have the exact hp needed I think.

**Comment by MeGaNeKoS** [comment]
The worst think is, Phalactery can kill enemy with 100 dmg, but you cant kill if you upgrade to khanda. 
My suggestion is, instead of ignore the dmg entirely, it should deal 100 flat dmg, plus 75% of current dmg. To counter that stupid SB build, this plus dmg should be nerfe by choosing the minimun either this 75%, or 30% of current max health.

**Comment by edsca** [comment]
think this is fixed now. Thanx folx!
