### ISSUE TITLE
Omniknight Repel can't negate pure damage which do not pierce debuff immunity

### ISSUE THREAD

**Issue by HD113904** [ValveSoftware/Dota2-Gameplay#14718]
### Ability name

Repel

### Description

As the description of debuff immunity,  debuff immunity can negate pure damage which do not pierce debuff immunity (like Tinker Laser,  OD Arcane Orb, etc).
But Omniknight Repel can not. By my test, all sources debuff immunity except Repel can negate. It is really wired.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107561734/bcf91027-922d-4e33-9e6a-ec3754be0a95)

### Example Match ID (and possibly Timestamp)

No response

**Comment by commentator24** [comment]
i might be wrong but i think what devs want to do is to eventually make debuff immunity have nothing to do with damaging debuffs. basically just mean you cannot be slowed or can tp while stunned if debuff immune. 

in the past they combined it together. if debuff immune, no magic or pure dmg from spells that does not pierce immunity etc. its either 100% or 0%. e.g. damaging debuffs like veno poison that cannot be dispelled or jak breath. some spells also say Cannot target immune etc. e.g tiny toss will say Nothing to toss..Debuff immune can be targeted but cannot be tossed. but this is silly and very annoying. I think they will eventually remove this, albeit rather slowly because of ongoing tournaments.

Now I think they want to make debuff immunity separate to bkb effects. bkb has added effects like +50% magic resist, +100% pure resist while active. so if pierce debuff immunity: yes these active effects are true (hence 0 pure damage if does not pierce), or false if no (still take 100%). this can allow greater flexibility like jug spin 80% magic resist instead of 100%. hence if pierce 80% ignored etc.

So debuff immunity should not mean that pure damage always deal 0 damage. That's bkb.
im not sure what you tested but if what you test is true then the rest are just briefly patched with tooltip and being really inconsistent here and there.

**Comment by HD113904** [comment]
> i might be wrong but i think what devs want to do is to eventually make debuff immunity have nothing to do with damaging debuffs. basically just mean you cannot be slowed or can tp while stunned if debuff immune.
> 
> in the past they combined it together. if debuff immune, no magic or pure dmg from spells that does not pierce immunity etc. its either 100% or 0%. e.g. damaging debuffs like veno poison that cannot be dispelled or jak breath. some spells also say Cannot target immune etc. e.g tiny toss will say Nothing to toss..Debuff immune can be targeted but cannot be tossed. but this is silly and very annoying. I think they will eventually remove this, albeit rather slowly because of ongoing tournaments.
> 
> Now I think they want to make debuff immunity separate to bkb effects. bkb has added effects like +50% magic resist, +100% pure resist while active. so if pierce debuff immunity: yes these active effects are true (hence 0 pure damage if does not pierce), or false if no (still take 100%). this can allow greater flexibility like jug spin 80% magic resist instead of 100%. hence if pierce 80% ignored etc.
> 
> So debuff immunity should not mean that pure damage always deal 0 damage. That's bkb. im not sure what you tested but if what you test is true then the rest are just briefly patched with tooltip and being really inconsistent here and there.

Fixed in 7.35c
