### ISSUE TITLE
Snowman observerward BUG *ingame*

### ISSUE THREAD

**Issue by Increase28** [ValveSoftware/Dota2-Gameplay#14763]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):

* Have you checked for system updates?: [Yes/No] yes
* Are you using the latest stable video driver available for your system? [Yes/No] yes
* Have you verified the game files?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. In-game play warding
2. Snow man observer ward cant deny when placed
3. -----

**Comment by abcdefghijken** [comment]
Seconded.

match id 7515202538

EVENT SNOWMAN WARD*

Pugna in dire is using Snowman ward, and multiple times I am unable to target the ward, only clicking on the floor and auto attack I'm able to click on the ward.

Please fix this! It's game breaking, we lost numerous fights because we cannot deward.

First instance of facing this bug is on bot lane in early game.

**Comment by Aluerie** [comment]
Duplicate #14638

**Comment by Nathanael-Valve** [comment]
Fixed
