### ISSUE TITLE
In-game guides not working.

### ISSUE THREAD

**Issue by Jewellyuser** [ValveSoftware/Dota2-Gameplay#14918]
I have no issues opening hero guides when I'm not in a match but as soon as I go in a match the guides won't load anymore.
I have tried " Allow downloads during game play - Clearing download cache - checking firewall - reinstalling steam - flushing DNS from cmd - changing DNS - changing internet connection ISP - unsubscribing and resubscribing to hero guides - verifying game files - everything you can think of... "

The only possible alternative way I came around was subscribing to a specific guide creator's guides in steam workshop using a chrome extension which subscribes to all user's created guides at once

**Comment by commentator24** [comment]
why dont you provide screenshots of what you see when you open shop and browse all guides in demo hero?
i'm guessing the chrome extension interfere with showing guides?

**Comment by Aluerie** [comment]
duplicate #13130

**Comment by Jewellyuser** [comment]
> why dont you provide screenshots of what you see when you open shop and browse all guides in demo hero? i'm guessing the chrome extension interfere with showing guides?

![Untitled](https://github.com/ValveSoftware/Dota2-Gameplay/assets/44063510/406ea228-6ee9-47a1-a2bb-784e31686248)
The chrome extension is a total different thing from the game, mate. I mentioned that I use that to subscribe to guides alternatively as a temporary fix! what does chrome have to do with in-game hero guides not being shown?

**Comment by commentator24** [comment]
ah sorry i dont know much, just guessing. the duplicate post alurie mentioned might help then https://www.reddit.com/r/DotA2/comments/18swz83/dota_2_guides_wont_load_fix/?rdt=44558
as far as i know those guides are steam guides with dota 2 template so it's like browsing websites through steam maybe? because it can take few seconds to load if the guide is long.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/2fa4c07f-cf0b-499d-8e09-d0efbfd5d856)
you can browse the steam guides and subscribe to add to a particular hero guide list in dota 2.
so if something is preventing you seeing these steam guides then you cant see them in dota 2 as well. Then i thought maybe your extensions or settings preventing / allowing it. e.g. it shouldnt be under steam workshop (or nothing to do with chrome extension as temporary fix) as thats the old guides i think? Or maybe your dota 2 setting is in another language than english, and some guides display characters that are not supported maybe? Just guessing. because mine only display English
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/8b031236-78af-445b-8141-b8efbe48d67b)

**Comment by Jewellyuser** [comment]
> ah sorry i dont know much, just guessing. the duplicate post alurie mentioned might help then https://www.reddit.com/r/DotA2/comments/18swz83/dota_2_guides_wont_load_fix/?rdt=44558 as far as i know those guides are steam guides with dota 2 template so it's like browsing websites through steam maybe? because it can take few seconds to load if the guide is long.
> 
> ![image](https://private-user-images.githubusercontent.com/109324155/296043738-2fa4c07f-cf0b-499d-8e09-d0efbfd5d856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDY5MzksIm5iZiI6MTcwNTAwNjYzOSwicGF0aCI6Ii8xMDkzMjQxNTUvMjk2MDQzNzM4LTJmYTRjMDdmLWNmMGItNDk5ZC04ZTA5LWQwZWZiZmQ1ZDg1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQyMDU3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTFjN2RlOWIzM2YxMzM5YWY2MGFlYzFjYjU2MzE0NzExODg3NDA1NjlkNTkyZmI5OTcyNTA3ODYxYTYyNDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AFQ_COB2dA0XwTPuvAWtrfgOgc7UzvfRY8JkNlA4uz8) you can browse the steam guides and subscribe to add to a particular hero guide list in dota 2. so if something is preventing you seeing these steam guides then you cant see them in dota 2 as well. Then i thought maybe your extensions or settings preventing / allowing it. e.g. it shouldnt be under steam workshop (or nothing to do with chrome extension as temporary fix) as thats the old guides i think? Or maybe your dota 2 setting is in another language than english, and some guides display characters that are not supported maybe? Just guessing. because mine only display English ![image](https://private-user-images.githubusercontent.com/109324155/296048033-8b031236-78af-445b-8141-b8efbe48d67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDY5MzksIm5iZiI6MTcwNTAwNjYzOSwicGF0aCI6Ii8xMDkzMjQxNTUvMjk2MDQ4MDMzLThiMDMxMjM2LTc4YWYtNDQ1Yi04MTQxLWI4ZWZiZTQ4ZDY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQyMDU3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTM2ZTNmZDA4MTVkZTc5ODgzZDc5MTBkMDJhZjQzZmNjZjVkZDUzN2MyODMxNzVmMDhlZThiYjg2ZWVmYzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lp_miYnvjArmwBAnHeOW96p-0EqAaX_jwozjnpAK4BA)


What I meant about that chrome extension is that I tried that extension that I open up steam workshop webpage and I click on the guide creator's profile and I subscribe to all of his guides with one click so that way the guides load.
but when I'm trying to access those guides in match that's not a possibility so that's why I'm calling the other method a temporary alternative way until they fix the issue.
