### ISSUE TITLE
Item disappeared shortly after purchase

### ISSUE THREAD

**Issue by patriksima** [ValveSoftware/Dota2-Gameplay#15038]
### Item name

Blade Mail 

### Description

The item was lost after being moved to another position shortly after it was purchased. I played Grimstroke.

### Example Match ID and Timestamp

7544986188 49:48

**Comment by Aluerie** [comment]
Erm, you put it into Ursa

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/d8a5ec98-07ca-443f-81d2-90c6960810c9)

**Comment by patriksima** [comment]
How? I replayed this slowly 0.25x and my mouse did not leave inventory. Or did?

**Comment by Aluerie** [comment]
hard to judge since replays don't have key press history but looks like that

This click is what triggered it, and further moving items in inventory doesn't cancel your current hero order which was to give out the item.

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/f4865151-767b-4ec5-af82-34775f4d6987)

**Comment by patriksima** [comment]
Ok, let's close it. Thank you for your time!
