### ISSUE TITLE
Lightning Hands (Arc lightning shard ability) does no damage 

### ISSUE THREAD

**Issue by Lame4Fame** [ValveSoftware/Dota2-Gameplay#15458]
### Description

I just drafted Arc lightning on Winter Wyvern in Ability Draft and bought the shard. I tried all combinations of toggling arc lightning alt cast on/off and toggling the lightning hands sub-ability on/off (not sure if the latter is supposed to be there to begin with since the shard text for AD suggests toggling the alternate cast of arc lightning) but it only resulted in either no lightning occuring, or the animation happening but dealing 0 damage.

Presumably this is only the case on base models other than Zeus, since I saw a youtube video from a few days ago of it working on him.
There is a reddit thread with other commenters having similar experiences so it seems like a general issue.
https://www.reddit.com/r/Abilitydraft/comments/1anlie4/has_anyone_seen_lightning_hands_in_actions_can/

### Example Match ID (and possibly Timestamp)

7586856641

**Comment by chrisf-valve** [comment]
This has been fixed with today's update. 

- You should no longer see Lightning Hands as an ability in your ability bar when you have the shard
- Arc Lightning Alt-Cast will now more reliably enable/disable the spell effects + damage
- If you create illusions while Arc Lightning Alt-Cast is enabled, the illusions now also should correctly using Lightning Hands when attacking.
