### ISSUE TITLE
Alt modifier keybind nolonger working

### ISSUE THREAD

**Issue by SpaZye** [ValveSoftware/Dota2-Gameplay#15545]
### Description

Alt-§ keybind nolonger works since The Dragon's Gift update.

Keybind shows up normally in the courier keybind settings, but alt modifier is missing in-game making "courier deliver items" or possibly any other ability unresponsive.

I am using a Finnish keyboard layout on Win 10.

### Screenshots

![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134627040/adc09779-cf99-4668-b13f-1f8e8a733279)
Keybind showing in the settings as normal.

![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/134627040/9146ecb0-e8c6-4f64-ae6d-e070d14d3353)
Keybind missing the alt modifier in demo mode when hovering over courier ability and can't be used.
Ability works normally when changed to any other keybind such as F1-5.

**Comment by SpiritWinD86** [comment]
After "The Dragon's Gift" update game having some issues with non english keyboard layouts and mb your issue is one of them.
Try to change keyboard layout to English before launching the game and in the game settings -> advanced hotkeys  -> check option "Bind keys based on keyboard position". mb it'll help.
