### ISSUE TITLE
Valve Anti-Cheat was unable to verify

### ISSUE THREAD

**Issue by Kr1st0fh** [ValveSoftware/Dota2-Gameplay#15978]
### Description

I'm getting this bug since months. I did everything I found online to try to fix it (run as administrator, delete bin folder, verify files, etc.) and I even reinstall the game, but the bug won't go away. I don't know what to do anymore. Any ideas?

### Screenshots

![imagen_2024-03-17_105055161](https://github.com/ValveSoftware/Dota2-Gameplay/assets/26170251/f0a7484b-ca7c-4338-b98c-949a6f97ff37)

**Comment by commentator24** [comment]
i dont know much abt computers but i think it's something to do with duplicate processes in task manager / cache not working properly. my understanding is cached data is saved so when you close the app, it reopens faster next time. but maybe sometimes harmless duplicates cause issues after an update because it's still there / cause memory issues? like when I reopen it, it automatically open duplicates that we dont really need to reuse. or maybe reuse wrong old process instead of newer process so VAC error pops up. 

e.g. i only have this chrome tab open but task manager says i have 8x  open, and 10x steam client web helper. even if i close chrome, the next time i reopen it automatically open 8x again because its cached.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/71fb73c9-425a-4b19-b640-92a16e48cfeb)

so last time VAC error happened to me i just clean windows cache, steam cache, and my internet cache. then make sure i have 2.4gb available space / memory.

go to steam settings > security > deauthorise all devices. then downloads > clear downloads cache.
Then check task manager end all steam processes, client web helper 1 by 1.
Then I open disk cleanup. clear temporary files to clean windows cache.
clean chrome cache not really important but maybe free up ram a bit.
then finally restart steam and login back again. hopefully that works for you

**Comment by Kr1st0fh** [comment]
> i dont know much abt computers but i think it's something to do with duplicate processes in task manager / cache not working properly. my understanding is cached data is saved so when you close the app, it reopens faster next time. but maybe sometimes harmless duplicates cause issues after an update because it's still there / cause memory issues? like when I reopen it, it automatically open duplicates that we dont really need to reuse. or maybe reuse wrong old process instead of newer process so VAC error pops up.
> 
> e.g. i only have this chrome tab open but task manager says i have 8x open, and 10x steam client web helper. even if i close chrome, the next time i reopen it automatically open 8x again because its cached. ![image](https://private-user-images.githubusercontent.com/109324155/313493831-71fb73c9-425a-4b19-b640-92a16e48cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTg4NTEsIm5iZiI6MTcxMDY5ODU1MSwicGF0aCI6Ii8xMDkzMjQxNTUvMzEzNDkzODMxLTcxZmI3M2M5LTQyNWEtNGIxOS1iNjQwLTkyYTE2ZTQ4Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxODAyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWM0YWIyYjA1NzEwZDdiMmY0NzY0OWNhNGI2ZjYyYzVmZGNlZTMwNDJiOTNjNmE2NWU4ZmU1MmUzYTcxMjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._TGKsvVFae1MI19oTTiQw32N8E2ZAypvrGvl0SYA2vs)
> 
> so last time VAC error happened to me i just clean windows cache, steam cache, and my internet cache. then make sure i have 2.4gb available space / memory.
> 
> go to steam settings > security > deauthorise all devices. then downloads > clear downloads cache. Then check task manager end all steam processes, client web helper 1 by 1. Then I open disk cleanup. clear temporary files to clean windows cache. clean chrome cache not really important but maybe free up ram a bit. then finally restart steam and login back again. hopefully that works for you

I tried everything still the same.

**Comment by Memoframe** [comment]
> i dont know much abt computers but i think it's something to do with duplicate processes in task manager / cache not working properly. my understanding is cached data is saved so when you close the app, it reopens faster next time. but maybe sometimes harmless duplicates cause issues after an update because it's still there / cause memory issues? like when I reopen it, it automatically open duplicates that we dont really need to reuse. or maybe reuse wrong old process instead of newer process so VAC error pops up.
> 
> e.g. i only have this chrome tab open but task manager says i have 8x open, and 10x steam client web helper. even if i close chrome, the next time i reopen it automatically open 8x again because its cached. ![image](https://private-user-images.githubusercontent.com/109324155/313493831-71fb73c9-425a-4b19-b640-92a16e48cfeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTE3NTEsIm5iZiI6MTcxMDc1MTQ1MSwicGF0aCI6Ii8xMDkzMjQxNTUvMzEzNDkzODMxLTcxZmI3M2M5LTQyNWEtNGIxOS1iNjQwLTkyYTE2ZTQ4Y2ZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwODQ0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2Y2NzBhNDgwMjk4MmE1ZDllMjZhMzNkNmJmNWU2NDAxNjYxNzFmNTNlNGZjMGYzNzdlODU5MDBmNGUxYzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8uAzA-Azmbc4oOMVs5JoO0nmt3CLMIcFT4bZHJdVEIM)
> 
> so last time VAC error happened to me i just clean windows cache, steam cache, and my internet cache. then make sure i have 2.4gb available space / memory.
> 
> go to steam settings > security > deauthorise all devices. then downloads > clear downloads cache. Then check task manager end all steam processes, client web helper 1 by 1. Then I open disk cleanup. clear temporary files to clean windows cache. clean chrome cache not really important but maybe free up ram a bit. then finally restart steam and login back again. hopefully that works for you

Several Chrome/Steam strings in your screenshot are just subprocesses: tabs and addons in Chrome; tabs in Steam Overlay browser and I guess some other stuff for Steam.

Subprocessing was done for stability so when something crashes it does not bring whole app down and to share load between different cores maybe.

When you clean browser cache in Steam, it's not only clears cache but also closes all opened tabs you did not bother to close yourself.

**Comment by Kr1st0fh** [comment]
FIXED by moving the game to another disk. You can move it back to the original one if you want, both disk should work by now.
