### ISSUE TITLE
Gyrocopter's Rocket Barrage (Magic) damage not increased by by Pugna's Decrepify

### ISSUE THREAD

**Issue by cputj** [ValveSoftware/Dota2-Gameplay#16059]
### Description

Gyrocopter's Rocket Barrage (Magic) damage not increased by by Pugna's Decrepify

**Comment by Aluerie** [comment]
733

**Comment by commentator24** [comment]
if pugna is enemy and cast on himself / his allies, it does not increase dmg.
if pugna is your ally and cast on enemy, it will increase rocket barrage dmg

**Comment by cputj** [comment]
Incorrect. Tested using Pugna as ally and casting Decrepify on an enemy, Rocket Barrage damage not increased.

**Comment by commentator24** [comment]
maybe you can show screenshots or video for the test you did? because mine show amplified dmg. e.g. 585 > 842 and 1700 hp vs 1486 hp
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/0c091884-fed5-4639-8a4d-2c699e9d92a3)

maybe you accidentally create enemy pugna instead of ally pugna?

**Comment by cputj** [comment]
Tested again, looks like you are right, very weird!
