### ISSUE TITLE
nyx mind flare does not bonus damage

### ISSUE THREAD

**Issue by kokhbaziplayer** [ValveSoftware/Dota2-Gameplay#16098]
### Ability name

mind flare

### Description

does not 25% bonus damage when target have 0 int an received damage in 15 sec past like ogre mage 

### Example Match ID (and possibly Timestamp)

0

**Comment by kokhbaziplayer** [comment]
> mind flare dmg is based on int multiplier... anything multiplied by 0 is 0 isnt it?
its true bot this line (Additionally deals damage equal to a percentage of damage the target received from Nyx in the past 15s.)where is it

**Comment by commentator24** [comment]
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/d79ed681-cc0c-42f2-9b54-7346c6479c5e)
so the first 2 mindflare is 0 dmg to ogre.. because ogre has 0 int.
then impale 210 ...25% of that is 39 minus 25% resist mayb.
then it reset back to 0 and start from 39? so 7.
then reset back to 0 and start from 7? so 1.
these happen within 6 seconds, so the damage doesn't accumulate 210 + 39 etc when it says the past 15 seconds. keep reset to 0 like visage 2nd skill

**Comment by kokhbaziplayer** [comment]
seems that effect on last spell used  :)
