### ISSUE TITLE
CVSoundTypeManager - GetSystemTimePreciseAsFileTime not supported on Windows 7

### ISSUE THREAD

**Issue by nmagane** [ValveSoftware/Dota2-Gameplay#16430]
### Description

Game suddenly does not launch on Windows 7 due to this one function it seems. Started happening with today's patch.
Can this be fixed?

**Comment by Amirrn84** [comment]
i having the same issue after the update 
here's the error i get when i run dota as administrator 
![Untitled](https://github.com/ValveSoftware/Dota2-Gameplay/assets/167531994/91df6e93-b599-418c-9ebe-7b3f085cd663)

**Comment by Amirrn84** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/16425

**Comment by Cooperfjh** [comment]
me too

**Comment by Cooperfjh** [comment]
> [Minimum supported client | Windows 8 [desktop apps | UWP apps]](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime)
> 
> I think Windows 7 support for Dota 11 has officially ended.

No replacement for this function?

**Comment by vehametra** [comment]
vxkex  устранил у меня данную проблему

**Comment by nmagane** [comment]
This issue has been fixed in a recent patch.

**Comment by Soroushie** [comment]
Had the same problem with the same exact error, only reinstalling the game will fixed it(I know, it takes hours but that's the only way)
But I have this huge fps drop which makes the game litterally unplayable...
Idk is it because of crownfall update or because my laptop's fan litterally stoped working the day before patch Xd
If you have win 7, let me know if you have fps drops too
