### ISSUE TITLE
Ward Bug that reveals an observer ward without having true vision

### ISSUE THREAD

**Issue by asmodeus941** [ValveSoftware/Dota2-Gameplay#1730]
### Description

In a recent Qojqva game, radiant gyrocopter was denying a dire sentry ward and gyro’s observer ward was revealed even though there was no vision of it.

### Example Match ID (and possibly Timestamp)

6653320803 - 11:34

**Comment by asmodeus941** [comment]
https://m.twitch.tv/clip/HeadstrongSpunkyPizzaTwitchRaid-m1psSf6wUF6bQIpf

**Comment by Aluerie** [comment]
This is not a bug.

https://dota2.fandom.com/wiki/Vision#Caster_Vision

> Caster vision is also applied upon launching an attack. The result of the attack does not matter, if the attack is executed, the  vision is granted.

> 150 radius ground vision around the casting or attacking unit which lasts for 2 seconds

Another quick fun example of it. I do not have `-allvision` but I see monkey on tree because Drow is attacking ally MK.
![image](https://user-images.githubusercontent.com/33165440/178074407-66472e31-dac7-429d-b761-678c550890f7.png)
