### ISSUE TITLE
Doom ultimate applies 4 times as much damage as normal

### ISSUE THREAD

**Issue by wpbernard** [ValveSoftware/Dota2-Gameplay#17546]
### Ability name

Doom

### Description

At one point late in the game, Doom casts ult on Dragon Knight. The ability description reads that it does 70 pure damage per second. However, with no other large damage sources, the beefy DK takes almost 4000 damage and dies from Doom alone. Upon inspecting the combat log, the debuff is proccing 4 times a second, as opposed to the normal 1 proc per second. DK has no status resistance or anything else that I could find that would incur any similar behavior as to increase the tick rate of Doom. Also something to note is the sound effect when Doom is initially cast on a target continues to repeat over and over on Dragon Knight until he dies; this behavior is despite the fact that the debuff (confirmed by combat log) is not refreshing/reapplying itself, which is another data point.  From the best of my memory, this sound replay was also occurring in real time when playing the match, and not just a replay bug. 

Trying to reproduce with all of the relevant heroes with their respective levels, items, and spell sequencing has so far been unsuccessful.

[Video with replay demonstrating the bug](https://www.youtube.com/watch?v=qo0DPTIU1tQ)

<img width="843" alt="2" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/2603277/f86b6284-36ed-4732-979d-2169aae12aa7">

<img width="906" alt="1" src="https://github.com/ValveSoftware/Dota2-Gameplay/assets/2603277/d3d05a95-3d01-47d7-926e-1e62d4679af6">

### Example Match ID (and possibly Timestamp)

7736706789 - roughly 78:35

**Comment by wpbernard** [comment]
Some stuff I've looked at:

Oracle I think is out of the picture, because even though fate's edict is cast, it happens a few moments after the bugged damage is being demonstrated.

DK has aghs, maybe it's applying doom to each form somehow? X ends the tick after DK ults, which was already mid-cast animation for Doom. Also CK used aghs ult after DK was X'd, and then DK activated BKB... The replaying sound effect (and the visual animation under DK's feet popping in and out) are probably the largest tell, but I'm not sure what to make of it yet. Quite a few moving parts here.

**Comment by ExplodedCow** [comment]
Got another example of this in 7736706789. I had a dig into it but never managed to find a specific cause, nor to replicate it. Image at the bottom is a great big info dump showing the items/buffs of all heroes involved, plus combat logs.

Doom worked normally up until 55:41, when it was cast on a Venomancer who was Soulbound to a Windranger. Both targets took 4x the damage (full damage and duration, but ticking 4x per second instead of once per second).

From that point on, Doom always did 4x damage for the rest of the game. There were two more casts of it, one with and one without Soulbind.

I tested a whole bunch of different setups based off this, with/without Soulbind, Ascetics Cap, other status resistance, anything that seemed relevant, but I never managed to replicate it.

![Dota Doom Bug Full Image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/107349075/fd009795-c962-44fc-9e95-fba06c9a2656)

**Comment by edsca** [comment]
The only common factor I can see between these two matches are that they are ticketed custom lobbies rather than public matches. We've had issues in the past with the game running slightly differently in public lobbies vs custom, e.g. Phantom Lancer causing insane frame drops in league matches but not pubs.

**Comment by edsca** [comment]
It has happened again in another league game

7748967536 64:25

**Comment by LightOfSeven** [comment]
We've not yet seen it since 7.36 but it has not been stated as fixed so the presumption is it may still be present. Please, if anyone else sees this bug, drop a comment here too especially if it's post-7.36 to confirm whether or not this is still happening.

**Comment by wpbernard** [comment]
https://old.reddit.com/r/DotA2/comments/1dw54y7/i_was_a_having_fun_with_planar_pocket_and_just/ interesting thread I saw that got me interested in this bug again.

I FINALLY sat down in demo mode and set host_timescale to max, and after idling for a few minutes, around 180 mins in and i was able to repro. The video doesn't show, but aghs isn't required. Dropping it and the bug is still there. So, you CAN do this in demo mode, and it seems to be attached to long-running games where some component of the spell breaks.

[Video repro](https://www.youtube.com/watch?v=h6C5frJAXsA)

**Comment by wpbernard** [comment]
fixed as of aug 2 2024 https://steamcommunity.com/games/dota2/announcements/detail/4335362463041041499
