### ISSUE TITLE
Aborting a teleport still puts your town portal scroll in cooldown

### ISSUE THREAD

**Issue by DipSwitch** [ValveSoftware/Dota2-Gameplay#1774]
### Item name

Town Portal

### Description

I don't know whether this is a bug or not, but if you use your town portal and abort it with the S key the town portal still gets a cooldown although you didn't really use it.

Other skills (epicenter) don't have there cooldown triggered if you do a last minute abort. (just after the green wait thing on the button has elapsed and the first wave has been released) so it's kinda inconsistent.

The message ID where I cancel epicenter after the first wave. Where I aborted the town portal I don't know anymore. Think this game as well but can't download the demo file anymore...

### Example Match ID and Timestamp

6645784546

**Comment by abdbuzurg** [comment]
The mechanic of tp consuming even after cancelling is left in the game from Warcraft 3. So it is not a bug. It was like that for ages. The

**Comment by DipSwitch** [comment]
It could however still be a bug. It could have been a bug in Warcraft 3 as well... What you don't use doesn't need to cooldown.

**Comment by DipSwitch** [comment]
But I guess it's more what you want to accomplish. I started teleporting to jungle, saw the offlane tower was being attacked, aborted, couldn't teleport to offlane tower anymore. While before that I could abort the epicenter without it being placed into cooldown.
The inconsistency feels like a bug, but maybe that's just me.

**Comment by althaj** [comment]
This is not an inconsistency, this is deliberately chosen so you have to think when using your TP scroll.

**Comment by BenjinZA** [comment]
There are also skills that will be put on cooldown even if you "abandon" it. For example, Echo Stomp (Elder Titan) has a 0.4 second cast time and a 1.3 second channel time. If the channel time is started and you cancel, the skill is on cooldown.

Town Portal Scroll, Boots of Travel and Boots of Travel 2 behave the same way. Once you start channelling, the item is put on cooldown regardless if you finish the channel or not.

This is not a bug, so you can close the issue.

**Comment by DipSwitch** [comment]
Ok, then epicenter is different than the rest, or they have literally decided per skill / item when the cooldown is triggered. I only had these 2 situations which acted differently.

**Comment by DipSwitch** [comment]
I'm still wondering if Valve shouldn't decide whether it's a bug or not, but whatever :D

**Comment by BenjinZA** [comment]
Definitely not a bug, it's been in the game since the start and even in Warcraft 3 Dota.

If Valve does change it (very unlikely) then it would be a balance change, not a bug fix.

**Comment by Cynaeon** [comment]
Just to make things clear since I don't feel like anyone did. Epicenter works that way because it is not a channeling ability, it just has a long cast time. Cast time is indicated by green fill on the skill icon.

![image](https://user-images.githubusercontent.com/21751144/179614146-1abd7e53-d3bf-4474-b911-bc1c8e4f3657.png)

While channeling is indicated by this big bar. 

![image](https://user-images.githubusercontent.com/21751144/179614074-e2198443-500e-4e02-a8de-51b45f3cce51.png)

When you start channeling then the ability is put on cooldown whether it was completed or not, and that's how every channeled ability works (spells like Witch Doctor's and Pugna's ults). On the other hand non-channeled abilities (like Epicenter) can be canceled whenever before the spell actually goes off, and it won't go on cooldown. So there is no inconsistency here.

> If you have two town portal scrolls, you teleport and abort you still have two, so why the cooldown?

You are mistaken, if you start stop TP channeling you lose that TP.
