### ISSUE TITLE
When playing with Riki you get assists if a teammate dies near you

### ISSUE THREAD

**Issue by MPucheta** [ValveSoftware/Dota2-Gameplay#1848]
### Description

We finished a match and noticed in the endgame screen that we scored 45 kills, although me as riki scored 4/12/44 (4 kills + 44 assists for a total of 48)

Watching the replay shows that a teammate dying near you gives you assists (but not gold associated, it just updates the score, not sure about relics). For example, in the match ID provided at 42:30, both my timber and void died and counted as assists.

 

### Example Match ID (and possibly Timestamp)

6666817474 - 42:30

### Screenshots

![image](https://user-images.githubusercontent.com/35865469/179448665-cd62ce2e-248d-457c-a228-bb370d04db57.png)

**Comment by ExplodedCow** [comment]
This is because of Smokescreen. You can read more details on the old Dev forum [here](https://dev.dota2.com/forum/bugs/gameplay-bugs/2267990-riki-smoke-screen-applies-a-non-affecting-debuff-to-allies-granting-assists) - I thought I'd copied that post over here already, but it appears I completely forgot :D

If an ally dies shortly after walking through Smokescreen, Riki gets an assist.

**Comment by TheUnholyWrath** [comment]
#83

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.
