### ISSUE TITLE
Nyx Mana Burn facet does not work.

### ISSUE THREAD

**Issue by jaccarmac** [ValveSoftware/Dota2-Gameplay#19094]
### Ability name

Mind Flare (and others)

### Description

The Mana Burn facet appeared not to work at all in this game.

### Example Match ID (and possibly Timestamp)

7774569416 - 01:00 (and the rest of the game)

**Comment by commentator24** [comment]
i tested in demo hero it seems you are right no mana burn at level 1.
the mana pool must be 500 before it starts burning mana at lv 1. around 72 dmg (70 doesnt manaburn)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/36b20e15-075a-4412-80fd-c393f89836ee)
but this is because of this alt tooltip
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/f864dfb7-f181-449d-8f47-a7441ab9d740)
so there's no bug here i think
