### ISSUE TITLE
QoP arcana is showing default legs in game

### ISSUE THREAD

**Issue by taurenrogue** [ValveSoftware/Dota2-Gameplay#2030]
EDIT: seems to be fixed now (7.32b)

### Cosmetic Item Name

Eminence of Ristul

### Description

Qop arcana is showing default qop legs in game instead of the arcana legs.

### Example Match ID

demo mode, bot game, and custom lobby

### Screenshots

![QoP_legs](https://user-images.githubusercontent.com/18579006/183568692-34097f05-a8c5-4973-94da-91cba259ec1d.png)

**Comment by ErikHumphrey** [comment]
Likely related to the new legs slot being added in-game, which awarded legs items for some older sets, but no legs slot item for Arcana owners. So I guess it uses the equipped default rather than the Arcana ignoring it due to the base model change.

**Comment by Astiberon** [comment]
![image](https://user-images.githubusercontent.com/107125193/184515546-9b5af48a-ec54-472a-ab97-20a3a134572a.png)

**Comment by shaileshgarg** [comment]
Lineage The Arch Temptress, should also get a leg slot item, as it changes the color of the default leg item.

**Comment by IngEyn** [comment]
#2019 also describes this bug.

**Comment by AncientsAndAntiques** [comment]
I spent some time testing the loadout behaviors, and here is my guess: As far as I can tell what is happening is that both player-made custom sets **and** Valve-made bundle sets do not contain instruction for the boot slot, because obviously the boot slot was just implemented recently.

End users reading: the solution to this is to equip a different boot, **then** equip the boot you want for your custom set, **then save the set again.** This will add an "equip this boot please" instruction to your set. If you use Valve-made bundles on shuffle you will need to make new custom slots until this issue is fixed.

If the loadout code checked which slots each hero/active persona had available when changing sets and then selected "default" for every slot that the set does not have instruction on, that could fix the problem across the board. This has also previously affected things like taunts, arcana, voice slots, costumes, et cetera.
