### ISSUE TITLE
Game stutters a lot with high FPS numbers and V-Sync ON

### ISSUE THREAD

**Issue by Endeavour18** [ValveSoftware/Dota2-Gameplay#20596]
### Description

I'm having massive performance problems with the game since forever, tried a lot of different configs (Dota and AMD's driver) and no sucess. Here are my PC specs. Windows 10 is in the last version and my video drivers too.

**The game runs smoothly when I spectate. The stutter only occours when I'm actually playing a match.**

![image](https://github.com/user-attachments/assets/fb11c5aa-2d2b-422d-9b57-4b8fb1addc78)
![image](https://github.com/user-attachments/assets/f68226b6-05db-4e78-84c6-c81d14efb80a)

Computer Information:
Manufacturer: ASUS
Model: System Product Name
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 5700X 8-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4000 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Windows 10 (64 bit)
NTFS: Supported
Crypto Provider Codes: Supported 311 0x0 0x0 0x0
Video Card:
Driver: AMD Radeon RX 6750 XT
DirectX Driver Name: atidx9loader32.dll
Driver Version: 32.0.11029.1008
DirectX Driver Version: 32.0.11029.1008
Driver Date: 7 15 2024
OpenGL Version: 4.6
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: AMD Radeon RX 6750 XT
VendorID: 0x1002
DeviceID: 0x73df
Revision: 0xc0
Number of Monitors: 2
Number of Logical Video Cards: 2
No SLI or Crossfire Detected
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 4480 x 1440
Primary Display Size: 23.54" x 13.23" (26.97" diag), 59.8cm x 33.6cm (68.5cm diag)
Primary Bus Type Not Detected
Primary VRAM Not Detected
Supported MSAA Modes: 2x 4x 8x
Sound card:
Audio device: SteelSeries Sonar - Media (Stee
Memory:
RAM: 32682 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: Undetermined
Total Hard Disk Space Available: 571108 MB
Largest Free Hard Disk Block: 173666 MB
OS Install Date: set 16 2023
Game Controller: None detected
MAC Address hash: 06b7279ea6d98e5e22689878e6bcad8b4c94b555
Storage:
Disk serial number hash: e021ac99
Number of SSDs: 3
SSD sizes: 240G,240G,120G
Number of HDDs: 0
Number of removable drives: 0

**Comment by commentator24** [comment]
whoa your resolution so huge 4480 x 1440?
chatgpt says check ram whether compatible with motherboard and CPU, may need to manually adjust to correct voltage and timings. power related / overheating issue? stutters usually because insufficient power or CPU/GPU overheat e.g. 80-90°C and throttle performance to cooldown.

Motherboard: Verify support through the motherboard’s manual or QVL list on the ASUS website.
CPU: The Ryzen 7 5700X supports high-speed DDR4 memory, but verify with BIOS settings.
BIOS/UEFI: Enable XMP/DOCP profiles to utilize the RAM at 4000 MHz. : Look for options labeled DRAM Voltage, Memory Voltage, or something similar. This setting controls the voltage supplied to your RAM. 1.35V is typically the correct and sufficient voltage.

Enter BIOS/UEFI: Restart your computer and enter BIOS/UEFI settings.
Locate XMP/DOCP Setting: Find the memory settings section and enable the appropriate profile (XMP for Intel or DOCP for AMD).
Save and Exit: Save your changes and exit BIOS/UEFI.
Run Memory Tests like MemTest86 or Windows Memory Diagnostic to ensure that your system is stable with RAM.

**Comment by IgorHoruzha** [comment]
@Endeavour18 Hello. Does Your issue look like this one #15078 ?

If You use Microsoft Defender Antivirus, could You try to turn off the real-time protection, please?

Could You provide a video of the issue, please? 

It may be useful to get as much as possible information to produce the issue on purpose. It will give a roadmap to developers and essentially increase the chances of fixing the issue(at least fast).

**Comment by Endeavour18** [comment]
@commentator24 It's because I use dual monitors I think

**Comment by Endeavour18** [comment]
@IgorHoruzha Hi! I'll turn the Defender off and do some tests and share it here, thanks for the reply!

**Comment by Endeavour18** [comment]
Update: turned off windows defender, undervolted my GPU, capped my FPS to 144, installed a VPN (in case of server ticks) and still no sucess, game still stutters.

**Comment by commentator24** [comment]
hang on a minute. why are you using XMP for intel if chatgpt says to use DOCP for AMD? arent you using AMD?

**Comment by Endeavour18** [comment]
@commentator24 yes I am, just checked my bios and DOCP is activated

**Comment by commentator24** [comment]
chatgpt says maybe 3 issues? primary VRAM not detected, primary bus type not detected, and sound card.
If the VRAM of a dedicated GPU is not detected, the system may fall back to other options for video memory. e.g. integrated graphics that use system RAM (main memory) instead of dedicated VRAM for graphical tasks. this is less efficient and slower compared to dedicated VRAM, which can lead to reduced performance and increased latency.

To address the Issue:
Verify GPU Installation properly installed in PCIe slot and that all necessary power connectors are securely attached.
Update or Reinstall Drivers and ensure the system correctly recognizes and utilizes the dedicated GPU.
Check BIOS/UEFI Settings and ensure the dedicated GPU is set as the primary graphics device in BIOS/UEFI. Look for settings related to GPU configuration or initialization.

Primary Bus Type Not Detected
The absence of "Primary Bus Type" detection could be due to various issues, including driver problems, BIOS/UEFI settings, or tool limitations. This means that the system information tool or diagnostic utility you’re using is not able to identify or report the type of bus used by your GPU or other components. 

Locate PCIe Settings:
Find PCIe Configuration: Look for settings related to PCIe slots or graphics card configuration. This might be under Advanced, Chipset, Integrated Peripherals, or similar tabs depending on your BIOS/UEFI layout.
Verify PCIe Slot: Ensure that the PCIe slot where your GPU is installed is enabled and configured correctly.
Set PCIe Mode (if applicable):

Select Mode: Some BIOS/UEFI setups allow you to select the PCIe mode (e.g., Auto, Gen 1, Gen 2, Gen 3). Set this to Auto or the highest version supported by your GPU and motherboard to ensure compatibility and performance.

Lastly sound card: an outdated or malfunctioning sound card can contribute to system stutters or performance issues, though it's typically not the primary cause. e.g. compatibility issues with the operating system, such as audio processing delays / increased latency that impact overall system performance, especially in intensive applications that are heavily reliant on real-time audio. An outdated sound card may struggle to keep up, resulting in stuttering or lag.

in dxdiag, check DirectX Version at the bottom of the window. Ensure you have the latest version of DirectX 12 installed. Go to the Sound tab to view information about your sound card and driver and ensure no problems found.
what directX are you using btw? it seems I also use 12

**Comment by Endeavour18** [comment]
@commentator24 Thanks for your help but the problem isn't my pc, it's Dota. I can play any other game without problem besides this game. Gonna try to sell my items and delete some friends on steam to see if helps, since when I play on my smurfs the game runs sooooo smoothly.

**Comment by IgorHoruzha** [comment]
> @commentator24 Thanks for your help but the problem isn't my pc, it's Dota. I can play any other game without problem besides this game. Gonna try to sell my items and delete some friends on steam to see if helps, since the game runs fine when I play on my smurf



Could You try to use all the default items like landscape, creeps and so on while playing, please?
Could You make record of the issue, please? (It is important to compare with other issues, and may be useful in understanding the 
 reason.)

**Comment by IgorHoruzha** [comment]
> @IgorHoruzha Hi! I'll turn the Defender off and do some tests and share it here, thanks for the reply!

It is important to turn of the real-time protection of Defender not just Defender. Have you tried so?

**Comment by Endeavour18** [comment]
So, after months of testing, I found a possible solution. It was Steam Cloud/remote user settings. I deleted everything from my userdata folder and Dota's folder (570) and disabled Steam Cloud sync for Dota. After that, I verified the game files and made my configs in game from scratch and now the game runs much better. It’s far from perfect, but it’s much more playable.

How did I come up with this solution? I borrowed an account from a friend (who has a lot of cosmetics, terrains, etc.) and played a match on it. Man, it was SO smooth; I was jealous. Then, I started comparing the userdata files and found out that my account had a lot of files that my friend didn’t have.

Before doing so, I cleaned my PC, reset the OS, disabled Windows Defender permanently, etc.

**Comment by commentator24** [comment]
whats the current file size? mine says 66gig
![image](https://github.com/user-attachments/assets/e70c90ea-41d3-4c60-95ec-183f2b2c8d44)

**Comment by IgorHoruzha** [comment]
> whats the current file size? mine says 66gig ![image](https://private-user-images.githubusercontent.com/109324155/360215518-e70c90ea-41d3-4c60-95ec-183f2b2c8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTM2MDMsIm5iZiI6MTcyNDU5MzMwMywicGF0aCI6Ii8xMDkzMjQxNTUvMzYwMjE1NTE4LWU3MGM5MGVhLTQxZDMtNGM2MC05NWVjLTE4M2YyYjJjOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxMzQxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDNkMjIxNmEzMjczOWQzYWJhNGIxZTAzNTZmOGQzZTk5NTgyMDBhOTAwMDcwNDYzNjcyOTk5MGFjNzUwY2NhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ypUBi47ya9s8ZBVPXOElr_K7ia5PR24urQI47nVr4s4)

![image](https://github.com/user-attachments/assets/38e7a6db-7ffd-40bc-89e2-be493d7b4131)
![image](https://github.com/user-attachments/assets/6d50cc02-1c6f-4b8d-835f-eca7fb48a606)

**Comment by IgorHoruzha** [comment]
> So, after months of testing, I found a possible solution. It was Steam Cloud/remote user settings. I deleted everything from my userdata folder and Dota's folder (570) and disabled Steam Cloud sync for Dota. After that, I verified the game files and made my configs in game from scratch and now the game runs much better. It’s far from perfect, but it’s much more playable.
> 
> How did I come up with this solution? I borrowed an account from a friend (who has a lot of cosmetics, terrains, etc.) and played a match on it. Man, it was SO smooth; I was jealous. Then, I started comparing the userdata files and found out that my account had a lot of files that my friend didn’t have.
> 
> @jeffhill you might wanna look at this. I can send more data if needed.

It sounds interesting, could You provide more data please.

**Comment by Endeavour18** [comment]
@IgorHoruzha sorry buddy, the game is stuttering again. I gave up. Thanks for the effort tho

**Comment by IgorHoruzha** [comment]
> @IgorHoruzha sorry buddy, the game is stuttering again. I gave up. Thanks for the effort tho

I see Your point, could You record stuttering, please?
