### ISSUE TITLE
Radiance shows wrong description

### ISSUE THREAD

**Issue by super-mario-beep** [ValveSoftware/Dota2-Gameplay#2106]
### Item name

Radiance

### Description

Radiance shows stats:
- 60 Damage
- 15% Evasion

but item description shows "... causes them to **miss 10%** of their attacks ..."

so which one is correct?

### Example Match ID and Timestamp

any match - any time

**Comment by zeroedout** [comment]
Ha, 23.5%. This is working as intended. From a [Reddit comment explaining it](https://www.reddit.com/r/DotA2/comments/t0o985/comment/hyb6dp8/?utm_source=share&utm_medium=web2x&context=3), "23.5 % for the holder , since the evasion and the miss are separated there is a 15% chance to miss because of evasion + 10% because of the aura - 10%×15% when both happen at the same time which gives you 23.5%"
