### ISSUE TITLE
VAC error when running dota with affinity parameter from cmd

### ISSUE THREAD

**Issue by zhdiv** [ValveSoftware/Dota2-Gameplay#21617]
### Description

Prerequisite: 

- [ ] OS: Windows 11

- [ ] Dota 2 is located on a different disk (you may need to adjust the shortcut for your system).

Create the following shortcut:

`C:\Windows\System32\cmd.exe /c start "" /affinity FF7F "D:\SteamLibrary\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe" -steam -novid`

Run the game from the shortcut and try to find a ranked matchmaking game. The game launched correctly all except core 7 (in my case); however, it is not able to verify that the machine is secure for matchmaking

![image](https://github.com/user-attachments/assets/ab09b2f0-7e8e-4562-9ab7-0b1e84742c39)

**Comment by cris458carlo** [comment]
Hello,

you’re trying to set up a shortcut to launch Dota 2 with specific settings and encountering issues with ranked matchmaking due to a machine security verification error. Let’s go through a checklist and steps to help resolve this issue:

1. Verify Command and Shortcut:
Ensure that your shortcut command is correct and properly formatted. Based on the information you provided, your shortcut should look like this: file:///C:/Windows/System32/cmd.exe%20/c%20start%20%22%22%20/affinity%20FF7F%20%22D:/SteamLibrary/steamapps/common/dota%202%20beta/game/bin/win64/dota2.exe%22%20-steam%20-novid

Here's a breakdown of the command:

C:\Windows\System32\cmd.exe /c start "" opens a command prompt window to run the subsequent command.
/affinity FF7F sets CPU affinity to limit the game to specific CPU cores.
"D:\SteamLibrary\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe" specifies the path to the Dota 2 executable.
-steam starts the game through Steam.
-novid skips the intro video.
2. Verify Steam and Dota 2 Integrity:
Sometimes, issues with security verification are due to corrupted files or outdated software. Try the following:

Verify Integrity of Game Files:
Open Steam and go to your Library.
Right-click on Dota 2 and select Properties.
Go to the Local Files tab and click on "Verify integrity of game files."
Update Steam Client: Ensure Steam is up-to-date.
3. Check Security Software:
Make sure your security software (antivirus/firewall) isn’t interfering with Dota 2 or Steam. You might need to add exceptions for both applications.

4. Check for Windows Updates:
Ensure that your Windows 11 system is up-to-date. Sometimes, updates can resolve compatibility issues.

5. Adjust Shortcut Settings:
If the shortcut isn’t working correctly, try creating a new one without specifying the CPU affinity to see if that resolves the issue. If it works, you might have to adjust the CPU affinity settings or test different values.

6. Try Running as Administrator:
Right-click the shortcut and select "Run as administrator" to see if it resolves the issue.

Hope that helps!

**Comment by zhdiv** [comment]
> Hello,
> 
> you’re trying to set up a shortcut to launch Dota 2 with specific settings and encountering issues with ranked matchmaking due to a machine security verification error. Let’s go through a checklist and steps to help resolve this issue:
> 
> 1. Verify Command and Shortcut:
>    Ensure that your shortcut command is correct and properly formatted. Based on the information you provided, your shortcut should look like this: file:///C:/Windows/System32/cmd.exe%20/c%20start%20%22%22%20/affinity%20FF7F%20%22D:/SteamLibrary/steamapps/common/dota%202%20beta/game/bin/win64/dota2.exe%22%20-steam%20-novid
> 
> Here's a breakdown of the command:
> 
> C:\Windows\System32\cmd.exe /c start "" opens a command prompt window to run the subsequent command. /affinity FF7F sets CPU affinity to limit the game to specific CPU cores. "D:\SteamLibrary\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe" specifies the path to the Dota 2 executable. -steam starts the game through Steam. -novid skips the intro video. 2. Verify Steam and Dota 2 Integrity: Sometimes, issues with security verification are due to corrupted files or outdated software. Try the following:
> 
> Verify Integrity of Game Files: Open Steam and go to your Library. Right-click on Dota 2 and select Properties. Go to the Local Files tab and click on "Verify integrity of game files." Update Steam Client: Ensure Steam is up-to-date. 3. Check Security Software: Make sure your security software (antivirus/firewall) isn’t interfering with Dota 2 or Steam. You might need to add exceptions for both applications.
> 
> 4. Check for Windows Updates:
>    Ensure that your Windows 11 system is up-to-date. Sometimes, updates can resolve compatibility issues.
> 5. Adjust Shortcut Settings:
>    If the shortcut isn’t working correctly, try creating a new one without specifying the CPU affinity to see if that resolves the issue. If it works, you might have to adjust the CPU affinity settings or test different values.
> 6. Try Running as Administrator:
>    Right-click the shortcut and select "Run as administrator" to see if it resolves the issue.
> 
> Hope that helps!

I found another solution: run Steam itself with an affinity setting so that it will also run game subprocesses with the specified affinity. This way, there will be no VAC warning in Dota 2.
