### ISSUE TITLE
Bug Report: Dota 2 Bingo Update Issue with Arcane Rune Progression

### ISSUE THREAD

**Issue by NicolasDutraMarzano** [ValveSoftware/Dota2-Gameplay#21636]
### Description

Hello,

I encountered an issue during the recent update to the Bingo event in Dota 2. I was progressing in a challenge that initially showed 0/7 with the use of kills while affected by Arcane Rune. After an exchange, the challenge progress unexpectedly changed to 1/23 to kills while affected by Arcane Rune.

Is this an intended change, or could it be a bug?

Thank you for your attention to this issue!

### Screenshots

![image](https://github.com/user-attachments/assets/24a8ee72-8b7b-422b-ba6b-4d67413843fa)
called "Ruína Arcana"

**Comment by eugene-valve** [comment]
Hi, by exchange do you mean a re-roll on the stat? It's possible your Arcane Rune kills rerolled into a stat with a different number of kills required for progress.

For example, it could have changed from "At least 3 kills occur with an Arcane Rune in a match." -> "At least 1 kill occurs with an Arcane Rune in a match."

**Comment by NicolasDutraMarzano** [comment]
I thought it could be a mistake since the number is a bit discrepant and before it was 0 completed and updated to 1.

**Comment by LokeLok** [comment]
@eugene-valve are the bingo tokens from playoff supposed to work on the group stage bingo card? I had 31 tokens left after upgrading most of the playoff bingo card, then I mindlessly went to the group stage bingo card and spammed 'shuffle card' until I had no tokens left. Turns out it used up playoff tokens, which seems wrong?

**Comment by LokeLok** [comment]
I also got 3 new tokens and they did not get added to the playoff bingo card, only to the international. This is not how it worked during the group stage.

**Comment by eugene-valve** [comment]
@LokeLok No, playoffs tokens should not be usable for the group stage card. But you can use group stage tokens on the playoffs.

There's been some similar feedback however that the token count being shown as shared is confusing, so we may update this so that you can use unlocked tokens on any phase in the future.

**Comment by LokeLok** [comment]
@eugene-valve  Thanks for the quick feedback. 

I just wanna clarify. I was able to use playoff tokens for the group stage earlier today. 

I also claimed tokens after a match 2 hours ago, which didn't get added to the playoff tokens but did get added to the international(during the group stage when you claimed tokens, they got added).

Both these two things are bugs, I assume?

**Comment by eugene-valve** [comment]
For the first: If you were able to use your playoffs tokens during group stage, that would be a bug. But your playoffs bingo card could have been showing you your group stage tokens as well, because the tokens would be combined between the two of them. The tokens are unlocked during a specific tournament phase, but they aren't treated as separate amounts.

Token Rewards always alternate between group stage, playoffs, and the international. So you can claim tokens for the international even if you're currently in playoffs.

**Comment by LokeLok** [comment]
That makes sense, thank you for helping out!
