### ISSUE TITLE
Blade Mail has no rebound damage while Duel PA 

### ISSUE THREAD

**Issue by iamjustadd** [ValveSoftware/Dota2-Gameplay#21749]
### Item name

Blade Mail

### Description

At game 7941216931 33:01, while I using Legion Commander to duel with PA. There are no rebound damge were counting. As I see there is no buff satan/reduce damage on PA. He should die before me.

### Example Match ID and Timestamp

7941216931 33:01

**Comment by Aluerie** [comment]
neutral

**Comment by iamjustadd** [comment]
I dont think it is be cause of neutral item
1. PA's neutral item is Mirror Shield which not have damge reduce and will double the attack power of the winning one in a duel.
2. I tried many times in playground, this bug may happend after PA Resurrection， if I use 否决(i dont know the name maybe reject/veto) before duel, PA will get a normal damage calculation, but I dont see any buff of PA are rejected.

**Comment by Aluerie** [comment]
Mirror Shield reflects Duel back on Legion Commander, meaning PA casts Duel on LC and not the original way around, and since PA has Aghanim Scepter, that ability is going to be Aghanim upgraded version, meaning Phantom Asssassin is Debuff Immune for the duration meaning she doesn't take damage from Blade Mail cause it does not pierce Debuff Immunity.

https://github.com/user-attachments/assets/072b20b3-459c-45b4-bd21-f96cc872be93

**Comment by iamjustadd** [comment]
I see that sounds correct.
