### ISSUE TITLE
Combination oversight

### ISSUE THREAD

**Issue by Debug-Client-Profile-1** [ValveSoftware/Dota2-Gameplay#2276]
### Item name

MageSlayer/BloodThorn

### Description

When you combine to the more expensive item you lose Magic Resistance.

The Match ID is irrelevant, just a random match I played recently.

### Example Match ID and Timestamp

6720510457

**Comment by ptohidi** [comment]
This is a very interesting issue, but I wanted to suggest you change the title. I personally had no idea what this issue was going to about be based on the title and before reading your detailed explanation. I would recommend something like "Bloodthorn magic res less than Mage Slayer" for the title.

**Comment by TheUnholyWrath** [comment]
Its been fixed. You can close this
