### ISSUE TITLE
Teleport Requires Hold/Stop causing wrong behavior of abilities that grant Invisibility

### ISSUE THREAD

**Issue by Phasmy** [ValveSoftware/Dota2-Gameplay#23297]
### Description

This is a problem that affects the proper interaction of items and spells that make a hero invisible such as Shadow Blade, Shukuchi, Trickster's Cloak, etc. The proper behavior is that these abilities may be cast after using teleport or a channeled spell without interrupting the channel. 
Currently enabling the setting "Teleport Requires Hold/Stop" incorrectly prevents the player from using these cloak abilities while channeling instead. 
There is no given match-id but this issue is easily replicated in a game or demo mode.

**Comment by commentator24** [comment]
whattt no way... all these years i thought only glimmer works
so its because of the setting :(

**Comment by seowth** [comment]
I agree and concur with the issue. Add Bounty Hunter's Shadow Walk ability to the list of abilities that is not interacting correctly with the setting enabled. The proper interaction is that Shadow Walk can be casted while the teleport is channeling so that you can go invisible while teleporting and start the cooldown of the ability.

Currently I have to disable the setting so that I can use Shadow Walk while teleporting correctly.

Please fix!!!

**Comment by SahilValve** [comment]
We've pushed an update that has fixed this. Thanks for reporting.

**Comment by seowth** [comment]
> We've pushed an update that has fixed this. Thanks for reporting.

Thank you, noticed this fix in game. We appreciate the prompt fix.

**Comment by commentator24** [comment]
pugna tp bug still not fixed btw XD
