### ISSUE TITLE
Game always crashed during loading

### ISSUE THREAD

**Issue by gxxx98** [ValveSoftware/Dota2-Gameplay#23302]
### Description

Game always crashed when loading hero-pick after accepted match or loading hero testing map,  everything is normal half a month ago

 I have tried various solutions, such as:
1.Adding "-vulkan" to the launch options.
2.Adjusting Windows Firewall settings.
3.Changing the compatibility settings for Dota 2 and Steam.
4.Uninstalling and reinstalling DOTA2 and Steam
5. Change all VIDEO setting to lowest
6. clean my memory module

Heres my crash log for your reference

[Uploading console.log…]()

**Comment by Velkix3** [comment]
The fix of that issue is ¿you remember the small window where you click verify integrity files? is in the same tab from that option but im refering about some space option used for launch option you add -map dota to load the map right when launching the game and not during pick phase, additionally you can configure the nvidia app on graphics tab, global settings tab there is an option named shader cache size and put it on 100 gb to fix unstability during in game matches like stutters or crashes

**Comment by Velkix3** [comment]
The fix of that issue is ¿you remember the small window where you click verify integrity files? is in the same tab from that option but im refering about some space option used for launch option you add -map dota to load the map right when launching the game and not during pick phase, additionally you can configure the nvidia app on graphics tab, global settings tab there is an option named shader cache size and put it on 100 gb to fix unstability during in game matches like stutters or crashes

**Comment by gxxx98** [comment]
Many thanks for your advise! 

I try to download dota2 from steamchina and then open it on steam, ant it works! But it's still crashed if i download game from steam. This is wired but it fix my issue.

**Comment by Velkix3** [comment]
you still finding crashes or playing normally after i suggested you the fix?

**Comment by gxxx98** [comment]
still crashed after your suggestion..
