### ISSUE TITLE
Doom goes on cooldown if enemy is untargetable while casting

### ISSUE THREAD

**Issue by SonNguyenTrong** [ValveSoftware/Dota2-Gameplay#2411]
### Ability name

Doom

### Description

Doom goes on cooldown if enemy is untargetable while casting
Ex: Enemy eul/ Storm start fly while Doom is casting make the skill goes on cooldown

### Example Match ID (and possibly Timestamp)

6725462899

**Comment by TheUnholyWrath** [comment]
Similar to #2397

**Comment by viksinha54** [comment]
Are you looking for one of the great casino website in India? No need to worry about that just visit at https://casinosbet.in/, here you can find out India's top most casino sites. choose the best sites & start earn money online at your place.

**Comment by Aniala123** [comment]
I want to share my personal recommendation, the best casino in Azerbaijan according to many gamblers is [https://pinupbet.az](https://pinupbet.az) This casino is notable for its pin-up design and a large number of popular games, as well as welcome bonuses for new members.

**Comment by Dota-Exp** [comment]
This will be fixed in the next update

**Comment by Koonus** [comment]
The phone is really a very useful thing. Especially in times of global quarantine . Because of the pandemic, I couldn't go outside and go to my favorite casino. During this period, the number of people playing online casinos has increased. According to statistics, the number of people playing free slot machines has increased by 50% compared to 2019. These numbers are understandable because many people try to avoid boredom during quarantine. Good casinos like parimatch casino were the best option for me. When I first want to https://parimatchbet-bd.com/casino/ I got good bonuses and I managed to play some slots for free. I really appreciate when a casino takes care of its customers.
