### ISSUE TITLE
If Hoodwink does not have enough mana for Ult, Aghs Copy will not Cast Ult

### ISSUE THREAD

**Issue by jaredeg** [ValveSoftware/Dota2-Gameplay#2532]
### Description

Per title - If you have Aghs, but not enough mana for y our ult, but cast your illusion. Your illusion will just run to the enemy.

Expected behavior, no where in aghs tool tip does it say you need enough mana to have copy cast ult, its expected if you can cast decoy, then it will cast ult.

**Comment by Mabadman** [comment]
I doubt this is a tooltip issue rather than a gameplay issue. 
It's counter-intuitive that a spell you can afford can't afford its own functionality. It's also a very edge case (only 2? heroes in the game with spell-casting illusions) and it probably wasn't accounted for. Otherwise it would've been mentioned in the patch notes.

![ezgif-2-d702f9994f](https://user-images.githubusercontent.com/42493726/187742319-76f60e8c-cf5b-41e9-84cf-ec72708e6c33.gif)

**Comment by Dota-Exp** [comment]
Will be fixed in upcoming update, thank you
