### ISSUE TITLE
Meepo with the first level of the ultimate can have two clones.

### ISSUE THREAD

**Issue by esz1** [ValveSoftware/Dota2-Gameplay#2572]
### Ability name

DIVIDED WE STAND + any other ability on meepo

### Description

Meepo on 5 lvl with:
**1 level Earthbind
2 level Poof**

Level ups ultimate, switches to clone through TAB and pumps any ability through him.
Result: **3 clones at level 5**

### Example Match ID (and possibly Timestamp)

6735243350

**Comment by JQINX** [comment]
Same. got destroyed in lane because of 3 meepo at lvl 4. 6734917983

**Comment by xksalol** [comment]
To shorten it:
Leveling any ability on a clone duplicates clone. Works at any level

**Comment by dobacetr** [comment]
Same here: 6735093964
Meepo saves a skill point until lvl4. At level 4 takes its ultimate to get a clone. Levels another skill to level 1 trough the clone to get another clone. Number of meepos seemed odd but i just chalked it up to missed patch notes on my part.
Where do we even report this intentional bug abusers?

**Comment by Sebyoo** [comment]
I also experienced this just now. On 3 min mark, meepo had already 3 clones in total. Please do check this bug. 6735790641

**Comment by Sebyoo** [comment]
![image](https://user-images.githubusercontent.com/112659906/188000556-16aea2db-5a44-4d50-b67d-3d2f538dd1c0.png)
Here's the proof of my recent game

**Comment by Nathanael-Valve** [comment]
Fixed as of BP shipping
