### ISSUE TITLE
MacBook’s Dota2 has no respond after updating

### ISSUE THREAD

**Issue by nikelsk8** [ValveSoftware/Dota2-Gameplay#2640]
### Description

The game was working fine before the new update. Now it doesn't start and the black screen stays with the dota logo...

**Comment by nich961996** [comment]
Same bro

**Comment by n0k8t** [comment]
Same. And saw many Reddit posts with same problem too

**Comment by prosdev0107** [comment]
Same here

**Comment by cesiumatom** [comment]
Issue persists after latest update.

**Comment by Mikimo153** [comment]
They usually take 2-3 days to fix mac launch problems, sadly :(

**Comment by xhffff** [comment]
same
os:mac os big sur 11.6.4
macbook air 2017 1.8 GHz Intel Core i5、
8 GB 1600 MHz DDR3

**Comment by su33u1411** [comment]
i was planning to play over long weekend;
looks like i wont be able to

**Comment by thanieljay** [comment]
Same here. It's not responding at all.

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
