### ISSUE TITLE
Game won't start on Macbook Pro 2018

### ISSUE THREAD

**Issue by Mikimo153** [ValveSoftware/Dota2-Gameplay#2644]
### Description

Whenever I launch the game, It opens up a black screen, usually, after this black screen, comes the intro animation; but as of now, all I get is a black screen.
Game won't fully launch and the more time I spend on the black screen, the louder the ventilators get.
This black screen displays the "loading clicker" that happens on mac.

specs:
MacBook Pro (15-inch, 2018)
Processor: 2.6 GHz Intel Core i7
Memory: 16 GB 2400 MHz DDR4

### Screenshots

<img width="1680" alt="Screen Shot 2022-09-01 at 21 34 31" src="https://user-images.githubusercontent.com/112676959/188054086-42504dd8-bf2d-4090-95c0-d3933e10d753.png">

**Comment by Varun271** [comment]
This is happening with mac, we have an issue open for this. Experiencing the same problem.

**Comment by JeffreyCheong** [comment]
Same

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
