### ISSUE TITLE
DOTA 2 DOES NOT OPEN ON MAC OS DEVICES!

### ISSUE THREAD

**Issue by bazarkua** [ValveSoftware/Dota2-Gameplay#2654]
### Description

DOTA 2 is not responding on MAC 0S devices. I have tried everything, reinstalling, deleting cache, changing launch options, etc, nothing helps. VALVE please fix...

**Comment by brocva** [comment]
SAME!! I just don't know what to do!

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
