### ISSUE TITLE
CANT OPEN DOTA ON MAC

### ISSUE THREAD

**Issue by brocva** [ValveSoftware/Dota2-Gameplay#2656]
### Description

I've tried everything but the app just doesn't run on my Mac since the newest update...

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
