### ISSUE TITLE
Dota not launching after update on Macbook 

### ISSUE THREAD

**Issue by etarzan** [ValveSoftware/Dota2-Gameplay#2659]
### Description

The game doesn't launch on my MacBook (2019 intel i9 16gb ram) after the latest update. 
None of the launch options works to even identify what the bug is at a user level. A dev could probably step through the start-up to figure this out

**Comment by etarzan** [comment]
@wykrhm This seems like something that a lot of people with *Unix based oses are facing and as a zero day issue. Is anyone even looking at this?

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.

**Comment by etarzan** [comment]
@Nathanael-Valve @danginsburg Thanks for the explanation update and the change being shipped. I deeply appreciate the response believe me I know how irritating it can be to have a public-facing product which has shipped with an issue
