### ISSUE TITLE
MAC OS NOT WORKING!

### ISSUE THREAD

**Issue by gadfsgadfga97** [ValveSoftware/Dota2-Gameplay#2660]
### Description

Mac OS cant launch Dota since BP patch. Help!

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
