### ISSUE TITLE
CANNOT LAUNCH DOTA BP FROM MAC OS

### ISSUE THREAD

**Issue by gadfsgadfga97** [ValveSoftware/Dota2-Gameplay#2661]
### Description

Pls help Mac OS hangs when launching dota 2

**Comment by ilongross** [comment]
I have the same error
MacOS Monterey v.12.2.1 (21D62)

**Comment by alfer-aws** [comment]
same:
Monterey v 12.5.1 (21G83)

**Comment by JeffreyCheong** [comment]
Same

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
