### ISSUE TITLE
MAC OS not able to run game

### ISSUE THREAD

**Issue by nich961996** [ValveSoftware/Dota2-Gameplay#2665]
### Description

Have not been able to start the game since BP

**Comment by panslava** [comment]
+1, when I launch it, it black window shows up, and the Dota2 process is not responding

**Comment by ilongross** [comment]
same

**Comment by Sotatek-TrungNguyen** [comment]
same

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
