### ISSUE TITLE
MAC OS Not working with BP Patch

### ISSUE THREAD

**Issue by nich961996** [ValveSoftware/Dota2-Gameplay#2668]
### Description

Volva pls fix bug thks

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
