### ISSUE TITLE
Cant launch DOTA2 from MAC OS

### ISSUE THREAD

**Issue by nich961996** [ValveSoftware/Dota2-Gameplay#2671]
### Description

The BP patch has cause my macbook to be unable to launch dota 2

**Comment by J4n92** [comment]
Same issue

**Comment by dieillusion** [comment]
the same

**Comment by MariusRossouw** [comment]
same issue

**Comment by JeffreyCheong** [comment]
Same

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
