### ISSUE TITLE
DOTA2 NOT OPENING MAC OS for over 10 hours

### ISSUE THREAD

**Issue by J4n92** [ValveSoftware/Dota2-Gameplay#2674]
### Description

Cant open dota2 after battlepass update for over 10 hours already. Pull it together Valve

**Comment by fahim0173** [comment]
#2599 #2675

**Comment by MariusRossouw** [comment]
same issue

**Comment by Loloner** [comment]
same

**Comment by JeffreyCheong** [comment]
Same

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
