### ISSUE TITLE
Dota 2 won't launch on Mac after battle pass update

### ISSUE THREAD

**Issue by HiroAsashi** [ValveSoftware/Dota2-Gameplay#2677]
### Description

Dota 2 shows black screen with spinning wheel after the battle pass update. Uninstalling both dota and steam and reinstalling both didn't fix the issue. None of the launch option (-vulkan, -vconsole, -autoconfig, -safe) worked.

The game was running fine on MacBook Pro late 2013 retina until this update.

Thank you.

**Comment by HiroAsashi** [comment]
The issue occurs on Mac OS Big Sur 11.6.8 (the latest update). Thank you.

**Comment by nikelsk8** [comment]
Same issue

**Comment by Megastar777** [comment]
Same with macOS Monterey

**Comment by cryptolove123** [comment]
Same issue with macOS Monterey 12.5.1

**Comment by MariusRossouw** [comment]
Same issue

**Comment by JeffreyCheong** [comment]
Same

**Comment by HiroAsashi** [comment]
Valve, you pushed out a small update today but the issue still persists. I still get the spinning beach ball with a black screen.

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
