### ISSUE TITLE
VALVE PLEASE FIX THIS ASAP!!! Dota 2 not working for MAC users

### ISSUE THREAD

**Issue by nich961996** [ValveSoftware/Dota2-Gameplay#2697]
### Description

Mac cant launch dota 2

**Comment by noisyboy1141** [comment]
why no one answering to ussssss.... valve what are u doing??????

**Comment by FanFanFantastic** [comment]
Do they not care about money anymore

**Comment by sergsibe** [comment]
time to remove dota2. GG

**Comment by sergsibe** [comment]
press F

**Comment by nobeard3** [comment]
Still doesn't work and I don't get it

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
