### ISSUE TITLE
fix this problem macbook won't enter the game anymore. VALVE!!! DOTA2!!!

### ISSUE THREAD

**Issue by dou189** [ValveSoftware/Dota2-Gameplay#2708]
### Ability name

fix this problem macbook won't enter the game anymore

### Description

fix this problem please macbook won't enter the DOTA2 anymore

### Example Match ID (and possibly Timestamp)

s

**Comment by nikelsk8** [comment]
SAME...

**Comment by Jhorev1l** [comment]
Same problem in the MAC, it shows only the black loading screen

**Comment by GrinningBobcat** [comment]
I’ve been trying the whole day…this sucks…valve please address this issue ASAP! ✌🏻

**Comment by nobeard3** [comment]
Still doesn't work

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
