### ISSUE TITLE
Valve Please Fix the Issue of DOTA 2 not Opening on Macs

### ISSUE THREAD

**Issue by nobeard3** [ValveSoftware/Dota2-Gameplay#2710]
### Description

I have been wanting to play on the new battle pass and new updates, and I simply can't. Its super demoralizing and I have read and done all the suggested ways to start the game. Started the game in "-safe" mode, nothing, started the game in "-autoconfig" mode, still nothing. Verified the game files, still nothing. Reinstalled the game, same issue. It opens and gets stuck on a black screen and the client stops responding. This issue is seen with almost all Mac users. Please fix it valve.

**Comment by fahim0173** [comment]
Mac Users being completely ignored 🤦🏽‍♂️

**Comment by Varun271** [comment]
[danginsburg](https://github.com/danginsburg) commented https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1236000031
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
