### ISSUE TITLE
DOTA Not Launching In MAC After Battle Pass Update! 

### ISSUE THREAD

**Issue by GrinningBobcat** [ValveSoftware/Dota2-Gameplay#2711]
A lot of MAC users are facing similar issue ever since the BP update. Valve do look into it immediately! Battle Pass or not…dota is my daily dose of serotonin…don’t leave us hanging in here!

**Comment by Nathanael-Valve** [comment]
Per Dan, I'm currently in the process of shipping this.

[danginsburg](https://github.com/danginsburg) commented 
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
