### ISSUE TITLE
Game doesnt run on mac!!! Please fixxxxx

### ISSUE THREAD

**Issue by BananaSmoker** [ValveSoftware/Dota2-Gameplay#2713]
### Description

After starting the game it gives me dotas logo and endless loading 

### Screenshots

# #
![Screen Shot 2022-09-02 at 20 04 21](https://user-images.githubusercontent.com/112721498/188207090-4d612c23-7a71-447e-a247-bcba780968b7.png)

**Comment by nikelsk8** [comment]
Same… zzzzz

**Comment by Varun271** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1235475208, we have an issue open as well

**Comment by FanFanFantastic** [comment]
same

**Comment by 4erepaxen** [comment]
Same

**Comment by FanFanFantastic** [comment]
this needs to be fixed today else valves gonna lose a lot of money

**Comment by nipeharefa** [comment]
same please fixed

**Comment by fahim0173** [comment]
guys its almost a 24 hours. Fix this please!

**Comment by eSargin** [comment]
please fixx!!!

**Comment by Varun271** [comment]
[danginsburg](https://github.com/danginsburg) commented https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1236000031
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.
