### ISSUE TITLE
Dota 2 can not launch on Mac, Big Sur 11.4 (20F71)

### ISSUE THREAD

**Issue by genisaretskiy** [ValveSoftware/Dota2-Gameplay#2730]
### Description

After updating, dota2 stopped launching, freezes at startup.
OS: Big Sur 11.4 (20F71)
Problem: can not start dota 2

### Example Match ID (and possibly Timestamp)

1111

**Comment by Varun271** [comment]
[danginsburg](https://github.com/danginsburg) commented https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1236000031
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.

**Comment by Nathanael-Valve** [comment]
Per Dan, this is fixed.
