### ISSUE TITLE
Wrong Movement Speed value on Warlock's Golem.

### ISSUE THREAD

**Issue by neoaraxis** [ValveSoftware/Dota2-Gameplay#2764]
Check Warlock's Golem stats.
![Warlock_Golem_lvl_1](https://user-images.githubusercontent.com/31570498/188276595-6c1da889-68a4-4723-8d0f-2f4134febadb.jpg)
![Warlock_Golem_lvl_2](https://user-images.githubusercontent.com/31570498/188276604-c390c49c-2b19-4317-aaaa-a20635ce2fab.jpg)
![Chaotic_Offering](https://user-images.githubusercontent.com/31570498/188298035-11c937ac-321e-418c-8b11-75f47cdbb060.jpg)

Stats
...
Movement Speed
320/340/360
...

edit: added chaotic offering image. updated description

**Comment by neoaraxis** [comment]
still not patched in 7.32d

**Comment by neoaraxis** [comment]
still not fixed.

**Comment by neoaraxis** [comment]
I hope we can get this fixed in the upcoming patch.

**Comment by neoaraxis** [comment]
still not patched lol.

**Comment by neoaraxis** [comment]
7.33 released update: still not patched

**Comment by neoaraxis** [comment]
BUMP! Issue still persists

**Comment by neoaraxis** [comment]
BUMP!

**Comment by neoaraxis** [comment]
BUMP!

**Comment by irismus** [comment]
**To note, this was implemented in 6.69.**
But at some point, around 7.30 to 7.33, the devs simplified the backend unit stuff. Instead of having 3 different Golems for 3 levels, they have the Chaotic Offering ability to overwrite the movement speed values of 1 Golem, effectively achieving the same goal.

However, I am suspecting that the ability values are not linked correctly (yet) like Beastmaster's Boar. Hence, having 320 movement speed for all levels.

This is reproducible in both Hero Demo Mode and in a local lobby.
The Golem has 320 movement speed the whole game (Match ID: 7346471420 Dreamleague S21).

Hope this gets fixed soon!

**Comment by neoaraxis** [comment]
> **To note, this was implemented in 6.69.** But at some point, around 7.30 to 7.33, the devs simplified the backend unit stuff. Instead of having 3 different Golems for 3 levels, they have the Chaotic Offering ability to overwrite the movement speed values of 1 Golem, effectively achieving the same goal.
> 
> However, I am suspecting that the ability values are not linked correctly (yet) like Beastmaster's Boar. Hence, having 320 movement speed for all levels.
> 
> This is reproducible in both Hero Demo Mode and in a local lobby. The Golem has 320 movement speed the whole game (Match ID: 7346471420 Dreamleague S21).
> 
> Hope this gets fixed soon!

Thanks for bumping the post.

**Comment by Aluerie** [comment]
This issue was always only visual UI so not a big deal. The Golems do get the bonus movespeed. Just look at how the higher level golem easily outruns the lower one in the following clip:


https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/2ed336a7-64b6-4e0d-96b9-0cf0b73d8198

Another way to confirm is to buy Warlock brown boots - he gets 345 ms and he can't outrun Golem lvl3 which has 360 ms (but UI shows 320)

**Comment by neoaraxis** [comment]
Visual? bug has been fixed.

Closing the thread.


![Golem level 1](https://github.com/user-attachments/assets/e06caa71-e962-4ed9-be02-e3fb853a7194)
![Golem level 3](https://github.com/user-attachments/assets/aacf6557-2e7a-4478-b47e-0ecd82d5bd3f)
