### ISSUE TITLE
Local Server doesn't allow peers to connect

### ISSUE THREAD

**Issue by gnugeist** [ValveSoftware/Dota2-Gameplay#2881]
### Description

Hosting private lobbies w/ custom bot scripts. As of today's update, nobody except host can connect to the hosting player. 

Tested:
Private lobby w/1-4 teammates, public server, any botscript: works
public lobby w/1-4 teammates, public server, any botscript: works
private lobby w/1-4 teammates, local server, any botscript: FAIL

![image](https://user-images.githubusercontent.com/62463669/188776688-f2603895-4d01-439c-9355-59b4f67c8691.png)

**Comment by Silvont** [comment]
`[NetSteamConn] Steam Net connection #1397491035 pipe closed by peer, reason 2055: NETWORK_DISCONNECT_LOOPDEACTIVATE
[NetSteamConn] CloseSteamNetConnection handle #1397491035 (userdata -1)
[NetSteamConn] Opened Steam Net Connection on socket 'client' to [A:1:2377837579:21256]:1, connection #4022415409 P2P steamid:90163288750091275 vport 0
[Networking] Created poll group for socket 'client'

[SteamNetSockets] src\steamnetworkingsockets\clientlib\steamnetworkingsockets_p2p_ice.cpp(736): We gathered candidate type 0x400, but 0x202 is allowed
[SteamNetSockets] src\steamnetworkingsockets\clientlib\steamnetworkingsockets_p2p_ice.cpp(736): We gathered candidate type 0x400, but 0x202 is allowed
[GCClient] Recv msg 7014 (k_EMsgGCOtherLeftChannel), 26 bytes
[GCClient] Send msg 7197 (k_EMsgGCMatchmakingStatsRequest), 8 bytes
[GCClient] Recv msg 7198 (k_EMsgGCMatchmakingStatsResponse), 300 bytes
[SteamNetSockets] [#4022415409 P2P steamid:xxxxxxxxxx vport 0] problem detected locally (5003): Timed out attempting to connect
[NetSteamConn] Steam Net connection #4022415409 P2P steamid:xxxxxxxxxxxxx vport 0 problem detected locally, reason 5003: Timed out attempting to connect
[Client] Failed to connect to [A:1:2377837579:21256]:1.  Reason code 5003.  Timed out attempting to connect
[Client] CL:  Server disconnected: 72: NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
[NetSteamConn] Closing Steam Net Connection on socket 'client' to [A:1:2377837579:21256]:1, handle #4022415409 (1000 CloseSocket)
[NetSteamConn] CloseSteamNetConnection handle #4022415409 (userdata -1)
[Networking] Summary of connection [#4022415409 P2P steamid:xxxxxxxxxxxx vport 0]:
[Networking]     End-to-end connection: closed due to problem detected locally, `

**Comment by jasontduncan** [comment]
:+1:

**Comment by gnugeist** [comment]
resolved with 9/12/22 hotfix update.
