### ISSUE TITLE
2 Bugs in 1: Critital Strikes damage do much less than the numbers marked above a player.

### ISSUE THREAD

**Issue by simplyexperimental** [ValveSoftware/Dota2-Gameplay#2899]
### Ability name

Mortal Strike

### Description

This may apply to other critical strikes from characters and items too.
I've always known that Wraith King's mortal strikes were way too weak....so I tested it in demo a couple times and yep it's completely bugged and it's been that way for ages. There are actually 2 bugs here:

TEST 1: In demo mode Right click using a level 6 wraith king for example with no abilities skilled.
The damage numbers that appear above the enemies head should match the hp that enemy lost.
So if the enemy has 700 hp and the right click deals 50 damage the enemy should have 650 hp left.

Everything is good so far.

TEST 2: Now skill the wraith kings mortal strike to level 1 that indicates that a 150% damage amp.
If wraith king has 60 Attack then 150% of that will be 60+90 damage = 150 damage.
However it seems to only to 50% more damage than your base for 90 damage.
So you're not actually doing 150% more damage you are only doing 50% more damage.
Somethings wrong there.

Next problem is the numbers that are shown for the critical strike not matching the actual hp loss.
TEST 3: Striking again with the same settings in test 2 I hit for about 80 damage but the numbers the critical
showed on the enemy was 180....so again something is very wrong here how can there be a 100 damage difference here?

The only conclusion I can see is the game code uses a:
Base damage x 1.5 which adds up to only 50% more damage rather the 150% damage listed by the mortal strike text.
Correct solution should be
Base damage + [base damage x 1.5] which means your base damage plus 150% more damage.
 

### Example Match ID (and possibly Timestamp)

Demo Mode with Wraith King

**Comment by TheUnholyWrath** [comment]
![20220908165128_1](https://user-images.githubusercontent.com/46859977/189054668-ebf01ce3-a908-4dcb-9a9c-edb6ce8045d0.jpg)

**Comment by dobacetr** [comment]
![image](https://user-images.githubusercontent.com/97127808/189094270-34fc7fce-7286-4221-a967-e534868e8df3.png)
This is completely intended. Critical Strike does not do 150% more damage. It does 150% damage.

![image](https://user-images.githubusercontent.com/97127808/189094691-a9230fcc-177d-4184-9bf6-be32a62ba258.png)
The tooltip suggest a bonus damage, but it does not state that the 150% is the bonus damage. Maybe the tooltip should be revised to say that it deals extra damage with a critical strike, rather than bonus damage. However, even as it is now; it does not mislead.
However, there is a tooltip error for the summoned skeleteons. That skill has been moved to Vampiric Aura. So, the additional detail should move moved as well.

**Comment by simplyexperimental** [comment]
It does mislead. It clearly states that you will deal 150% "bonus damage" via a critical strike. Traditionally calculations like these have always used a x multiplier and never a percentage based one. So the simple fix may be to just change the % to an x.

If I get a wage of 20$ an hour and I got a 100% bonus I would be getting 40$ an hour. 150% bonus would mean even more.
But if I got 20$ an hour and got a 1.5x bonus I would be getting 30$ an hour and this matches the internal results of the game.
Based on the final results so far if i hit for 60 damage and I crit for 150% I only do 90 damage which is a 1.5x multiplier and not a 150% multiplier these calculations will produce different results.

If you want to continue to use the % option then "Wraith kings next strike will deal amplified damage to the enemy. 50%/90%130%/170%  These numbers fit the actual internal calculations.

=================
Also the damage above a players head should always reflect the final damage they take after reductions.
That's what it's purpose is isn't it? What's the point of seeing values from a critical strike that have nothing to do with actual damage taken. What's the point of seeing 2k crits when the actual damage is only 400???

**Comment by dobacetr** [comment]
The tooltip does not state that "the crit deals %150 bonus damage". It says that WK deals bonus damage with it, and shows the critical multiplier to be 1.5x or %150. Both are the same thing. If it said BONUS DAMAGE: 150%, then it would have been misleading. This way, it is ambiguous at best.

Also, note that this would mean something entirely different. Bonuses are computed with respect to base damage rather than the full damage. So, it would imply that only base damage would be amplified. Check Earth Shaker's _Enchant Totem_ ability for reference.
![image](https://user-images.githubusercontent.com/97127808/189200164-4f1342f5-2861-4da4-a356-0b9f03217d76.png)
![image](https://user-images.githubusercontent.com/97127808/189200202-1b9b9cbc-653d-430d-bae4-a029fabf32b7.png)
ES with Rapier, upon casting _Enchant Totem_ receives only his base damage as bonus (100% at level1).

===========
![image](https://user-images.githubusercontent.com/97127808/189198400-9fa221cd-42d6-4291-b898-dbf0c16bd532.png)

In the above picture, the Wraith King has battlefury + 25% cleave talent, equalling 95% cleave. The pink Tiny has 6 platemails, while the other Tiny has none. When WK hits the Tiny with 60 Armor (78% Reduction) it takes 129 damage. However, the Tiny at the back takes 417+149 damage (70% and %25 cleave). The red crit indicator was about 600. So, here's what happens:

1. WK deals ~600 crit damage to pink Tiny.
2. WK cleaves off of this damage twice, %70 for his Battle Fury, 25% for his talent.
3. a) The pink Tiny reduces this damage by 78% and takes 129 damage.
b) The Tiny at the back takes 2 instances of cleave damage which are 600 * 0.70 and 600 * 0.25. Both instances are reduced by its own physical reduction (0% because he had 0 armor). It takes 417 and 149 damage.

As you can see, the cleave depends on the damage before reductions and each unit reduces the damage by its own reduction. Thus, the red numbers are always relevant.

(It appears they removed the Kunkka's _Tidebringer_ exception. It now behaves fully consistent with other cleave sources)

**Comment by dobacetr** [comment]
![image](https://user-images.githubusercontent.com/97127808/189202394-4d46fc72-7497-4c1b-acd3-e31df8cf1be5.png)
Looking carefully to the numbers, there is something else weird happening. Both Tiny'es has 0 armor.
WK has 121-123 Damage range with level 20, 25% Cleave talent and nothing else.

Sometimes WK deals his proper damage which is in range 121-123. Then the cleave damage is indeed 25%.
However, sometimes WK deals 105-107 Damage: There are 2 problems with this.
1. These damage values are not within WK's damage range.
2. WK cleaves only for ~13% of the damage (14 damage out of 107).
Someone should verify if this is specific to the Demo mode; or if this happens in the actual game. I will try to test other heroes as well.  This damage discrepency happens without the 25% Cleave talent.

**Comment by TheUnholyWrath** [comment]
> **Possible Bug**
> 
> ![image](https://user-images.githubusercontent.com/97127808/189202394-4d46fc72-7497-4c1b-acd3-e31df8cf1be5.png) Looking carefully to the numbers, there is something else weird happening. Both Tiny'es have 0 armor. WK has 121-123 Damage range with level 20, 25% Cleave talent and nothing else.
> 
> Sometimes WK deals his proper damage which is in range 121-123. Then the cleave damage is indeed 25%. However, sometimes WK deals 105-107 Damage: There are 2 problems with this.
> 
> 1. These damage values are not within WK's damage range.
> 2. WK cleaves only for ~13% of the damage (14 damage out of 107).
>    Someone should verify if this is specific to the Demo mode; or if this happens in the actual game. I will try to test other heroes as well.  This damage discrepency happens without the 25% Cleave talent.

Melee hero damage block

**Comment by TheUnholyWrath** [comment]
> Melee heroes now have damage block of 16?

50% chance to block 16 damage. Can't remember when it was added

**Comment by dobacetr** [comment]
Yes, it appears it was added with Void Spirit patch. I must have completely missed it as i was not playing anymore. I will add an addendum to the previous posts.

**Comment by simplyexperimental** [comment]
Ok So after considering the critical strike works as intended to not include the base damage and we include
the 15 damage block melee heroes have and 20% damage reduction from having 4 Armour it all adds up everything checks out.

It would be nice if the critical strike damage showed the actual damage they took after reductions. 
Why have white damage numbers pop up showing the real damage they took and then have crits showing damage that's not accurate.

I suppose you can close this case now if there's nothing left.
Thanks a lot for helping out everyone.

**Comment by dobacetr** [comment]
> Ok So after considering the critical strike works as intended to not include the base damage and we include the 15 damage block melee heroes have and 20% damage reduction from having 4 Armour it all adds up everything checks out.
> 
> It would be nice if the critical strike damage showed the actual damage they took after reductions. Why have white damage numbers pop up showing the real damage they took and then have crits showing damage that's not accurate.
> 
> I suppose you can close this case now if there's nothing left. Thanks a lot for helping out everyone.

The original value(red crit numbers) is used for cleave. That is why it is still useful. Also, you are not able to tell the illusions apart from the crit values either. You have to pay attention to actual damage dealt, accounting for the armor.

Also, note that some these aspects are leftover from the Dota 1 days. It showed damage before reductions as well.

**Comment by simplyexperimental** [comment]
Thank you.
