### ISSUE TITLE
Bug or Feature : Monkey king Aghs' soldier breaks smoke if smoke is clicked in the vicinity of the soldier.   PS : It does not break it if you are smoked before meeting the soldier. 

### ISSUE THREAD

**Issue by LSZDota** [ValveSoftware/Dota2-Gameplay#3073]
### Ability name

Monkey King Aghs

### Description

https://user-images.githubusercontent.com/113470686/189989645-eb468842-b63f-4a15-b60a-901e461dbcb5.mp4

### Example Match ID (and possibly Timestamp)

Demo

**Comment by commentator24** [comment]
seems like a bug since it doesnt break if already smoked.
i think mk soldier is based on real hero template as untargetable hero clone so it breaks smoke.
similar behaviour with arc clones. casting smoke when enemy arc clone nearby will break invisibility, yet doesnt break when the clone walk towards smoked hero.
yet inconsistent with meepo clones, as any meepo clones will break invisibility

**Comment by TheZett** [comment]
This is intended.

When they nerfed the Tempest Double to not break smokes anymore, they applied this change to all non-Meepo clones.

But to prevent people from being able to freely escape from non-Meepo clones (like it used to be the case for Smoke vs Brewlings), they made Smoke still check for all clones upon cast and only apply the Smoke buff, if no clones are within the detection AoE.

**Comment by commentator24** [comment]
oo didnt think of that. 
should close the thread then
