### ISSUE TITLE
Puck talent on 30 lvl

### ISSUE THREAD

**Issue by pudgepiska** [ValveSoftware/Dota2-Gameplay#3641]
### Description

When puck pick dream coil in ability draft, he has only left talent

### Example Match ID (and possibly Timestamp)

6789198169

**Comment by TheUnholyWrath** [comment]
#3127 #627

**Comment by visuran** [comment]
In a similar fashion, how about Shadowfiend? He can stomp around with the magic talents and be able to be decent in the lategame because of the physical ones. Furthermore, while 40% cd reduction was always too good to pass up, having the armor talent at lvl 25 with the aura on buildings one makes pushing the whole enemy base a joke[,](https://tinytask.pro/) and ratting a lot more viable. Maybe it’s gonna be too late tho.

**Comment by TheUnholyWrath** [comment]
This has been fixed, you can close this issue.
