### ISSUE TITLE
Featured Hero Position is too Far to the Left

### ISSUE THREAD

**Issue by jeffercize** [ValveSoftware/Dota2-Gameplay#384]
### Description

On the profile page the featured heroes are too far to the left and can easily cover up parts of the last match and other UI elements, there is extra space to the right which is where it used to be about a year ago.

*Tested on 2560x1440 Borderless Window*

### Screenshots

![Capture1](https://user-images.githubusercontent.com/15132507/171857029-711142e8-1cb6-428f-8af6-7202fb33afd6.PNG)
![Capture2](https://user-images.githubusercontent.com/15132507/171857037-c954d168-5614-43be-aba4-618d65609104.PNG)

**Comment by AeonDota** [comment]
The problem becomes much worse when you use a hero with a big model.

![image](https://user-images.githubusercontent.com/106765027/172251326-b7336595-c8ba-435e-8d07-05011d520922.png)

**Comment by shaileshgarg** [comment]
> The problem becomes much worse when you use a hero with a big model.
> 
> ![image](https://user-images.githubusercontent.com/106765027/172251326-b7336595-c8ba-435e-8d07-05011d520922.png)

The hero preview element should be behind the other elements on the profile page.

**Comment by anko** [comment]
I found a workaround, with a console command:

    dota_preview_hero_x_offset -100

That moves the featured hero to the right. You may want a different number depending on your screen size; I'm not sure what the units are.

Notes:
- The console command is not persistent if you just run it in the console once; it clears when you restart Dota. To make it persistent, you can run it automatically on every start by putting it in the `autoexec.cfg` file, in the folder `cfg` in your game data folder.
- This also affects the featured hero's position during pick (after you've picked a hero). That means it won't be centred anymore which looks odd, but since it's displayed behind all UI in that context, it won't block anything either.
- The showcased hero position does not immediately update if you already have the profile screen open when you run the command. To see it update, you have to change to another screen, then back to your profile.

**Comment by shaileshgarg** [comment]
Issue no longer relevent.
