### ISSUE TITLE
Maledict damage pierces BKB

### ISSUE THREAD

**Issue by BaiBuaBok11** [ValveSoftware/Dota2-Gameplay#4430]
### Ability name

Witch Doctor - Maledict

### Description

Magical burst damage from maledict burst pierces even if I press BKB to get magic immune.

I get a little test with Oracle - Fate's edict, the damage from Maledict is not piercing through in this case.

![image](https://user-images.githubusercontent.com/36475889/198702103-928d2ccf-fb32-4e85-a394-b8cdf2d17754.png)

### Example Match ID (and possibly Timestamp)

6828296464 - 11:39

**Comment by BaiBuaBok11** [comment]
I test this mechanic with another spell that doesn't pierce magic immunity but can't be dispelled (e.g. Venomancer - poison nova), the damage doesn't pierce through both BKB and Fate's edict.

**Comment by TheUnholyWrath** [comment]
> Magical burst damage from maledict burst pierces even if I press BKB to get magic immune.

BKB doesn't make you magic immune, it makes you spell immune. You can still take Magic damage while BKB is active. Maledict says it doesn't pierce spell immunity because you can't cast it on someone who is currently spell immune. Maledict dealing damage to you when you BKB after getting affected by Maledict is it interacting correctly. You should close this.

> I test this mechanic with another spell that doesn't pierce magic immunity but can't be dispelled (e.g. Venomancer - poison nova), the damage doesn't pierce through both BKB and Fate's edict.

This test does nothing to back up your point, the spells don't interact with Spell Immunity the same way at all. Here's the alt text for Poison Nova: "The Poison Nova debuff will still be applied to Spell Immune targets but will not deal damage as long as they remain Spell Immune.".

**Comment by Daar543** [comment]
I guess there must be the confusion since there is only one label for "pierces spell immunity", and it's not expicitly stated which part of spell immunity it should not pierce.

**Comment by BaiBuaBok11** [comment]
> > Magical burst damage from maledict burst pierces even if I press BKB to get magic immune.
> 
> BKB doesn't make you magic immune, it makes you spell immune. You can still take Magic damage while BKB is active. Maledict says it doesn't pierce spell immunity because you can't cast it on someone who is currently spell immune. Maledict dealing damage to you when you BKB after getting affected by Maledict is it interacting correctly. You should close this.
> 
> > I test this mechanic with another spell that doesn't pierce magic immunity but can't be dispelled (e.g. Venomancer - poison nova), the damage doesn't pierce through both BKB and Fate's edict.
> 
> This test does nothing to back up your point, the spells don't interact with Spell Immunity the same way at all. Here's the alt text for Poison Nova: "The Poison Nova debuff will still be applied to Spell Immune targets but will not deal damage as long as they remain Spell Immune.".

Well, from this reply I assume that there is more hidden skill detail in "alt text" like the one you mention with poison nova, but how can we access this detail from in-game (or elsewhere)? Can you just put this detail in the skill description like poison nova doesn't deal lethal damage for more clarification?

I don't use GitHub a lot but I assume that if I close this issue we can't talk about this issue again, so I'll leave it open for a bit longer.



> I guess there must be the confusion since there is only one label for "pierces spell immunity", and it's not expicitly stated which part of spell immunity it should not pierce.

That's the point, my assumption on not piercing spell immune means the damage doesn't pierce through BKB like in poison nova description, but as I test further along with @TheUnholyWrath reply, the damage from seld maledict (12/18/24/30 dps) doesn't pierce through BKB but the burst damage does.

What exactly does "PIERCES SPELL IMMUNITY: No" means anyway? is it for the damage or the debuff status?
- Maledict "PIERCES SPELL IMMUNITY: No" = no damage from self-skill, can't apply debuff but burst damage can pierce through BKB.
- Poison Nova "PIERCES SPELL IMMUNITY: No" = no damage from self-skill but can apply debuff on BKB.

**Comment by BaiBuaBok11** [comment]
Oh.. my bad I just learn that you can press the alt button to see more detail in the in-game skill description haha, but can you add bursting damage piercing through BKB in alt text or something? it would be nice.

my apology to @TheUnholyWrath for not knowing what alt text mean.

**Comment by TheUnholyWrath** [comment]
Okay so I went back as far as I could and it seems like everyone, me included, could be wrong about this. The wiki has documentation for this change but there is no official documentation (I can find) for this, seems to have either been accepted as a feature or has been a bug since 7.23. The only thing that makes me think it might be intended was when it was changed in 7.23 both the DPS and the burst damage pierced BKB, at some point since then it was changed to only the burst damage piercing BKB (with 0 official documentation). #294 also reported this and got nuked. 

Its up to you if you want to leave this open, I'll delete my first comment since I can't actually find what it was supposed to be based on. 

For Github you can close issues and we can still comment on them. 

Poison Nova seems like a stupid exception that makes the Pierces Spell Immunity tag weird. It seems like it should be whether or not you can cast the spell and it will affect units that currently have Spell Immunity. The Venomancer tag change came in 7.23 and makes no sense to me but I could just be misunderstanding all of this.

**Comment by yckmm** [comment]
It was a general change to how spell immunity works in 7.23, Note 2 is what applies here. (Venomancer ult is the exception that proves the rule or something.)

Spell Immunity no longer grants 100% Magic Resistance (this means that all spells that are able to pierce spell immunity now deal damage as well)
Note 1: A quick refresher on how this currently works: Spells have two properties: 1) whether it applies to Spell Immune targets, and 2) what the damage type is. These are listed in the ability tooltips.
Note 2: This change means that if something pierced immunity before, and was magical damage, it will now do damage. If it didn't pierce spell immunity before, it will still not deal any damage.

**Comment by BaiBuaBok11** [comment]
> ou magic immune, it

I'm aware of magic resistance but since Maledict has 2 damage sources, from self DPS and bursting damage from missing HP, both damage should apply with the same mechanic but now it isn't.
