### ISSUE TITLE
M1 Mac > Dota 2 Constant Crashing after update

### ISSUE THREAD

**Issue by stphnfld** [ValveSoftware/Dota2-Gameplay#4708]
Game will not open in Vulkan, OpenGL crashes constantly. Can't play game at all.

Video settings don't seem to matter, was fine pre-update.

**Comment by cesiumatom** [comment]
Same on AMD Radeon 560.

**Comment by Varun271** [comment]
Same for intel chip a well....i am in game and game crashes suddenly

**Comment by RiptidePzh** [comment]
same issue !

**Comment by taurenrogue** [comment]
opengl crashes constantly on linux 2... vulkan on nvidia gpu doesnt work for 3 weeks now... but hey who cares now that we already payed

**Comment by Varun271** [comment]
I dont know what these people do before releasing the update..do they even care to check if everything is working fine or not

**Comment by Varun271** [comment]
@danginsburg can you please look into it...its been a really bad experience after the last two major updates for MAC users.

**Comment by Varun271** [comment]
@Nathanael-Valve

**Comment by stphnfld** [comment]
Game is now only crashing every time a TP is used. Pls fix, I don't want another abandon because of this stuff.

**Comment by shadowdive10** [comment]
Macbook pro M1 (2020) here

Can also confirm Vulkan doesnt work with dota since the first week of October. Game crashing just by trying to start it from steam.

Been forced to manually initiate with OpenGL ("-gl" on lauch options)

Since Battle Pass Update part II OpenGL crashes during any games (specially during visually intensive Ultimates, like Monkey King's). Game closes suddenly.

**Comment by kumel619** [comment]
try "-gl" on lauch options

**Comment by krav559108** [comment]
same here
