### ISSUE TITLE
Diretide skin stuck in candy workshop.

### ISSUE THREAD

**Issue by Niquell** [ValveSoftware/Dota2-Gameplay#5384]
I spent a lot o rerolls on my Candy Workshop and this Warlock skin was stuck on the left slot since last week.

![image](https://user-images.githubusercontent.com/32531466/201506769-486bc42d-9abb-4fbf-b8ad-ac5b81f7649a.png)

![image](https://user-images.githubusercontent.com/32531466/201506781-c57184ff-43ab-43de-86ed-da940c20ef28.png)

**Comment by SatanRunsSeaWorld** [comment]
This is not a bug,

If you've bought all other diretide cosmetics and warlock is the only one you havent bought it will always show up in the left-most slot because thats where all the diretide cosmetics show up (it's just how they have candyworks set up)

You have to purchase it or it will keep appearing until you do, lowering your chance of getting an arcana greatly.

**Comment by zjm1993828** [comment]
How many diretide cosmetics does valve has in this shop? I think I've only bought the cosmetic of roshan. Does that means that there's only tow cosmetics in this position?

**Comment by Debeluk** [comment]
> How many diretide cosmetics does valve have in this shop? I think I've only bought the cosmetic of roshan. Does that means there are only tow cosmetics in this position?

6. 3 Couriers, Ward, Roshan, Warlock Set.
