### ISSUE TITLE
(Hoodwink) Acorn Shot not providing bonus attack range & Bushwack bad tree priority

### ISSUE THREAD

**Issue by Hatsura** [ValveSoftware/Dota2-Gameplay#5656]
### Ability name

Acorn Shot, Bushwhack

### Description

**Acorn Shot (Q):**
Leveling up this skill is not providing bonus attack range, which should be clearly perceptible (provides 125/200/275/350 bonus range).
This bug probably appeared with changes to acorn shot in patches 7.29~7.30 onwards, i think. In early patches this skill did give a laning advantage, despite bushwack being more reliable.

**Bushwhack (W):**
This skill is latching heroes/units towards their nearest tree instead of latching to the tree nearest to the skill's cast point. 
This can lead to unpredictable latching behaviour leading to units being latched to trees far apart. The level 25 AoE talent can make this effect even more noticeable.

Expected:
Units should get latched to the tree closests to the center of the Bushwhack (ie.: skill cast point).

_Tests were done in Hero Demo mode and in a custom match lobby with cheats enabled (-createhero -wtf -gold -lvlmax)._

### Example Match ID (and possibly Timestamp)

N/A

**Comment by LauriVahosalmi** [comment]
_"Acorn Shot (Q):
Leveling up this skill is not providing bonus attack range, which should be clearly perceptible (provides 125/200/275/350 bonus range)."_

 **- You mistook the ability description. Acorn Shot never gave passive attack range, only on the active one and it still works as intended.**

_"Bushwhack (W):
This skill is latching heroes/units towards their nearest tree instead of latching to the tree nearest to the skill's cast point.
Expected:
Units should get latched to the tree closests to the center of the Bushwhack (ie.: skill cast point)."_

**- This is not a bug. The ability description clearly states that 'Affected enemies take damage and are pulled towards the tree nearest to them' so it clearly is intended behavior.**
