### ISSUE TITLE
Cant sell Warlock and Sven TI10 immortals.

### ISSUE THREAD

**Issue by jerrinctom** [ValveSoftware/Dota2-Gameplay#5733]
### Description

I was trying to sell Warlock and Sven TI10 Immortals and I cannot list them. It says this item cannot be listed in steam community market. I have sold all the rest just these two have a bug please fix them, so that I could buy more immortals from the community market with the income of the sale

### Screenshots

	
![image](https://user-images.githubusercontent.com/119467093/204688815-ced35309-5322-4491-917b-cd1513610678.png)

**Comment by Timeline12** [comment]
I would like to express my gratitude to you for sharing this excellent post. I have to say that I am very impressed with your post because the information provided is both comprehensive and simple to grasp. Your subsequent post will receive a lot of attention from me. [nytimes crossword](https://nytimescrossword.io)

**Comment by shaileshgarg** [comment]
#5011

**Comment by jerrinctom** [comment]
Sorry for the late reply, i never thought you guys would reply that's why. Anyways yes its fixed Thank you
