### ISSUE TITLE
Auto Attack: Never STILL auto attacks

### ISSUE THREAD

**Issue by westonleavitt** [ValveSoftware/Dota2-Gameplay#5736]
### Ability name

Auto Attack

### Description

My heroes will ALWAYS Auto Attack regardless of what my settings are on unless I explicitly press H for hold position. It kills me constantly in situations where I don't want to be seen. Attached is a video where I do nothing but right click near creeps and you can see the issue.

I have reinstalled the game multiples times and tried tweaking every setting and nothing affects it. the behaviour does not occur on friends PCs.

Attached is the video demonstration:
https://streamable.com/u7f1db

### Example Match ID (and possibly Timestamp)

6893191256

**Comment by LokeLok** [comment]
Toggle autoattack setting overrides the auto attack setting. Since it's switching between auto attack(on) and standard auto attack rules. Go to option and set a hotkey for toggle autoattack, if you don't have it already. Toggle it as off while ingame, you can do this in demo mode. 

![options](https://user-images.githubusercontent.com/106764092/205002311-e9dc29f3-dd6f-4acc-9bc4-44e286743bfb.png)

**Comment by westonleavitt** [comment]
Works. Thanks
