### ISSUE TITLE
Your decency - Incorrect text with player ID on Your decency page

### ISSUE THREAD

**Issue by AnIHULI** [ValveSoftware/Dota2-Gameplay#5793]
1. Open dota 2
2. Click on nickname
3. Click on Your decency button

ER:
Should be text "Your ID::" or "ID:"

AR:
Text is (translated into english) "Friend ID:"
![1](https://user-images.githubusercontent.com/50448341/205447503-0ba9a3b7-e7e4-4db5-951a-8dc556af5582.png)

I think that is issue because it is mine ID and not my friend ID

**Comment by TheUnholyWrath** [comment]
This is translating correctly, in English it shows as "Friend ID"

**Comment by AnIHULI** [comment]
> This is translating correctly, in English it shows as "Friend ID"

But should be "Friend ID" instead "My ID"? It is my ID and not a friend ID

**Comment by TheUnholyWrath** [comment]
Seems like you're overthinking it. It'd be called a Friend ID because you use it to add friends. Calling it My ID or Friend ID or just ID has basically no difference, the label doesn't really matter and its just a number unique to your account, calling it Friend ID makes it more obvious that you can add people by entering this number.
