### ISSUE TITLE
Riki's Smoke Cloud does not work when combined with Rubick's stolen Smoke Cloud

### ISSUE THREAD

**Issue by aquasarus** [ValveSoftware/Dota2-Gameplay#6429]
### Ability name

Smoke Cloud/Spell Steal

### Description

This issue is easily reproducible, but I also have a match ID as a live example since that's how I discovered it.

Match ID 6955164111
Timestamp: 15:20

The problem can be summarized as follows:
**When Riki's Smoke Cloud gets combined/overlapped with Rubick's Smoke Cloud (or vice versa), a hero is only affected by the first Smoke Cloud they enter.** For example (assuming Riki and Rubick are on opposite teams):
* If Riki casts Smoke Cloud on himself, then Rubick casts Smoke Cloud on Riki (overlapping the first Smoke Cloud), RIki will not be silenced.
* If Rubick casts Smoke Cloud on Riki, then Riki walks into his own Smoke Cloud (overlapping the first Smoke Cloud), Riki will still be silenced.
* If Rubick casts Smoke Cloud on an allied hero, then an enemy Riki casts Smoke Cloud on the same hero (overlapping the first Smoke Cloud), that hero will not be silenced.

You can test the interaction easily in demo mode. This applies to both the silence and the miss chance. The main reason I'd consider this a bug is because the behavior relies on which Smoke Cloud collides with the hero first, which makes it very hard to predict the outcome during a team fight.

### Example Match ID (and possibly Timestamp)

6955164111

**Comment by shaileshgarg** [comment]
#561

**Comment by TrentFoulds** [comment]
The issue you're encountering may be because Riki's and Rubick's abilities are likely to be different abilities, even though they may have similar effects. When Rubick steals an ability, it takes the exact version of that ability from the hero it is stolen from. If the stolen ability has different properties or behaviors from Riki's original ability, it may cause compatibility issues.

It is possible that the combination of Riki's and Rubick's abilities may not be intended by the game developers, and as a result, the abilities may not work as expected.

If you continue to encounter issues, I recommend checking the game's forums or seeking support from the game developers to see if they have any information or solutions to offer.

**Comment by TheUnholyWrath** [comment]
This has been fixed. You can close this issue.

**Comment by aquasarus** [comment]
Nice! Verified.
