### ISSUE TITLE
Static field not working

### ISSUE THREAD

**Issue by Grit0801** [ValveSoftware/Dota2-Gameplay#6634]
### Description

Kinetic Field Disruptor skill not working on ability draft game mode. Skill used on Natures Prophet

### Example Match ID (and possibly Timestamp)

6970211660

**Comment by TheUnholyWrath** [comment]
You haven't provided any information about how or when you think the spell isn't working correctly. We can see that when the field has formed it is working correctly because it blocks Sand King in at 7:10. I'm assuming you think the bug occurred (at least) at 11:12 when Lich walks out of the field at the very end of the Formation Delay, as you almost entirely stop casting the spell after that point. Lich does something similar at 8:33 as well, also walking out of the field at the end of the Formation Delay. I can't see any evidence of Kinetic Field working incorrectly, you're welcome to investigate yourself if you think I'm wrong. Otherwise you should close this issue.

**Comment by Grit0801** [comment]
Thanks
