### ISSUE TITLE
Battlepass 2022 MMR DOUBLEDOWN TOKENS are missing

### ISSUE THREAD

**Issue by centralnui** [ValveSoftware/Dota2-Gameplay#6641]
### Description

Today Ive realised that MMR DOUBLEDOWN TOKENS are missing too!
These are had NO "Seasonal" flag! I paid real money! You didnt say that these will dissapear when battlepass ends!!!!

### Screenshots

![20230115125734_1](https://user-images.githubusercontent.com/113243212/212525315-10ed92b7-51fe-4409-aaba-c717e49c965e.jpg)

**Comment by TheUnholyWrath** [comment]
You've created 3 issues for 1 problem on 3 different items. Can you please close all 3 issues (#6641, #6587, #6586) and create a new issue (or rewrite and retitle this issue) suggesting that these 3 items be labelled properly if they return in the future. This repo has enough bloat and duplicate issues already, and if you find anything else not clearly labelled as temporary/seasonal you can just add to that one instead of creating a new issue. Thank you
