### ISSUE TITLE
Should I be considered as a SMURF?

### ISSUE THREAD

**Issue by shizhec** [ValveSoftware/Dota2-Gameplay#6768]
### Description

I believe that my newer account got banned as a Smurf (Quene time  almost forever after 11 games win stack)
1. I win a 11 stack
2. the account level is 25 with steam level 0
3. I win 11 games within a week.

The Rason I don't think that I should be accused as a Smurf is:
1. None of my dota2 account excess 4000mmr So I consider myself winning 11 stack because of 40% luck + 60% skills
2. I play multiple roles during 11 games, not only carry.
3. I'm busy with my research so that I only have time playing dota during the Chinese new year.
4. I don't play my main account since I want to practice my skill using another account

I would be appreciated if any dev could show up and help me with my issue and let my continue play my test account

### Screenshots

![image](https://user-images.githubusercontent.com/36945506/215257413-2cf5eb43-606e-4c35-b86c-97f39ad6de24.png)
![image](https://user-images.githubusercontent.com/36945506/215257427-afdaee72-17c5-4bae-a12a-6788b2546333.png)

**Comment by commentator24** [comment]
So you're not banned, but think you're banned 😆 just showing off 11 win streaks? 🤣  
If you are banned you will see that matchmaking blocked for at least a year / forever.
it just takes longer time to search because not many lv 25 accounts are legend 5 on 11 win streak.  it needs to find similar skilled opponent. Probably will only find game when you meet someone on 10-11 winning streak as well, or maybe not many ppl playing at that time.

I think no issue to have 2nd acc to practice. you will only get banned if valve suspect you are doing suspicious activity like cheating using scripts/3rd party programs; concealing identity (someone else playing your acc /"friends" asking you to play their acc e.g. suspicious playing location; or avoiding punishment timer); selling accounts / boosting MMR e.g. promoting to win party mmr for money / gift in return privately etc; intentionally ruin games / bad behaviour and get multiple reports etc.

so should be fine if you're using the same computer to play, and only playing solo

**Comment by shizhec** [comment]
> So you're not banned, but think you're banned 😆 just showing off 11 win streaks? 🤣 If you are banned you will see that matchmaking blocked for at least a year / forever. it just takes longer time to search because not many lv 25 accounts are legend 5 on 11 win streak. it needs to find similar skilled opponent. Probably will only find game when you meet someone on 10-11 winning streak as well, or maybe not many ppl playing at that time.
> 
> I think no issue to have 2nd acc to practice. you will only get banned if valve suspect you are doing suspicious activity like cheating using scripts/3rd party programs; concealing identity (someone else playing your acc /"friends" asking you to play their acc e.g. suspicious playing location; or avoiding punishment timer); selling accounts / boosting MMR e.g. promoting to win party mmr for money / gift in return privately etc; intentionally ruin games / bad behaviour and get multiple reports etc.
> 
> so should be fine if you're using the same computer to play, and only playing solo

Thanks for the clarification! Really appreciated!
Seems the only way to queue quicker is to lose some games🤣
Anyway I will close this issue.
