### ISSUE TITLE
Weekly quests bug

### ISSUE THREAD

**Issue by PblSmrnv** [ValveSoftware/Dota2-Gameplay#6888]
### Description

For the last few weeks, no games have counted for Cavern Crawls or Weekly Quests.

ID:  219438531

ex. 6993432762, 6997778082 were played as test games, but no other were counted as well

### Example Match ID (and possibly Timestamp)

ex. 6993432762, 6997778082

**Comment by Aluerie** [comment]
ehm, Battle Pass ended one month ago meaning you can't complete anything anymore, Battle Pass page only exists so people can claim the stuff the might have forgotten to.
 
![image](https://user-images.githubusercontent.com/33165440/217068054-83563f87-b3e4-4b03-a32b-d26933c6f99b.png)
---

since there is no bug, please close your issue.

**Comment by PblSmrnv** [comment]
my bad, i thought i can still finish weekly quests.
