### ISSUE TITLE
Monkey King Loadout Spawn Animation not played anymore

### ISSUE THREAD

**Issue by shaileshgarg** [ValveSoftware/Dota2-Gameplay#6988]
### Description

When monkey is opened in Hero Loadout, he plays a initial spawn animation. That animation is not playing anymore and MK is just standing there.

What it is supposed to be.
https://youtube.com/clip/Ugkx4cdCZpARVOUYswUDmOuNQ5GdTBEwvzD0

**Comment by Aluerie** [comment]
all fine on my end. cant reproduce;

**Comment by shaileshgarg** [comment]
Still doesn't work on my end, I have been messing with Workshop tools in Dota lately, could be due to that.

**Comment by shaileshgarg** [comment]
Reinstalling the game also didn't fix it.

**Comment by Aluerie** [comment]
Huh, further playing around with it - I didn't see any issues because Arcana one works fine (and your clip references arcana):

https://user-images.githubusercontent.com/33165440/219941840-08a44adf-484f-4c5a-9d08-8b1394688997.mp4

But you are right, default one is just standing there: 

https://user-images.githubusercontent.com/33165440/219942109-c53fc4a9-e041-4e02-bdc4-76145bd62ceb.mp4

---
oh well, sorry, let's reopen the issue. But what if loadout animation is arcana feature? I genuinely don't remember, not a MK player. However, wiki page doesn't list it as one so most likely not.

**Comment by shaileshgarg** [comment]
No its plays regardless of arcana. All heroes have a Loadout Spawn animation, monkey king seems to be only broken one.
