### ISSUE TITLE
networth problem after the game 

### ISSUE THREAD

**Issue by gdelfs** [ValveSoftware/Dota2-Gameplay#7090]
### Description

networth bug after the game id 7034189177 on medusa that i was playing. it's showing 5k instead of ~65k

### Example Match ID (and possibly Timestamp)

7034189177 - after the game

### Screenshots

![image](https://user-images.githubusercontent.com/25989571/221386204-fd6d0cdc-15a3-4949-95f4-feafce137ae2.png)

![image](https://user-images.githubusercontent.com/25989571/221386205-bed8522f-fd77-47b6-a418-0362742f0f2d.png)

**Comment by gdelfs** [comment]
Obs: I did not sell/break any items
obs 2: i had 2 rapiers in the base backpack, maybe that was what caused the error, dont know..

Best greeting, love dota 2 !

**Comment by TheUnholyWrath** [comment]
This is a duplicate of #214. Please close this issue

**Comment by asasd325** [comment]
really it's a duplicate of #214?

**Comment by Alexiscarters** [comment]
The "net worth problem" is a term used to describe the financial difficulties that some professional athletes face after retiring from their sport. Many athletes earn large sums of money during their playing career, but may struggle to manage their finances effectively, leading to financial instability once their career comes to an end. This can be caused by a variety of factors, including lack of financial education, overspending, and reliance on unreliable sources of income. To avoid the net worth problem, it's important for athletes to plan for their financial future and seek out professional advice to help them manage their wealth effectively.

**Comment by gdelfs** [comment]
> The "net worth problem" is a term used to describe the financial difficulties that some professional athletes face after retiring from their sport. Many athletes earn large sums of money during their playing career, but may struggle to manage their finances effectively, leading to financial instability once their career comes to an end. This can be caused by a variety of factors, including lack of financial education, overspending, and reliance on unreliable sources of income. To avoid the net worth problem, it's important for athletes to plan for their financial future and seek out professional advice to help them manage their wealth effectively.

nonsense.

**Comment by gdelfs** [comment]
Yes, a duplicate of https://github.com/ValveSoftware/Dota2-Gameplay/issues/214. Issue Closed.
