### ISSUE TITLE
Rank medal

### ISSUE THREAD

**Issue by RedVampirium** [ValveSoftware/Dota2-Gameplay#7131]
### Description

In my profile my rank is herald 4 but when i enter the game at ranked  it says i am herald 3.
In my profile it used to tell me the percentage below medal now i cant , i am dota plus member.
Please check if something is wrong if it is possible. Thank You

**Comment by shaileshgarg** [comment]
You haven't provided your steamid or userId, how can someone check?

Were you playing Ranked Roles, because the Medal shown during pick phase is according to your comfort with the role selected.

**Comment by RedVampirium** [comment]
Steam ID: 76561199319275076
my steam id sorry

**Comment by commentator24** [comment]
Medal shown during pick phase can be either your actual MMR or adjusted according to your performance / party.
e.g. if partied with someone, maybe it'll show +1 star herald 4 becomes herald 5 during pick phase.
e.g. if adjusted due to role performance, my medal shown during pickphase as pos 2 is archon 3, but when i play pos 1 it's crusader 5 (i only play pos 1 like once a year) 
e.g. if medal shown is herald 3 and you cant see percentage, this is your actual MMR because you've been losing. the medal will only update to herald 3 if you're under the required MMR for herald 3.
assume required MMR for herald 4 is 460 MMR and you currently have 400 mmr. even though you're still herald 4, pick phase will show herald 3. assuming herald 3 is 320 MMR, when you keep losing to 300 MMR your medal will be updated to herald 3.

you can check your MMR under profile stats. and you can update MMR after each game by editing anything in profle or restart dota, otherwise it will show previous game %
