### ISSUE TITLE
control group bug

### ISSUE THREAD

**Issue by Akz77** [ValveSoftware/Dota2-Gameplay#7144]
### Description

the functionality for "next unit" and "prev unit" in control groups is bugged. instead of cycling between units in the current control group it cycles between control groups themselves.

**Comment by Akz77** [comment]
ah thanks for the reply. i tested again and realised the condition.

So the next unit/prev unit for selecting units within a control group now considers the same _type_ of unit as a single unit. 

Example: If invoker and his summons are in the same control group, the 'next unit' hotkey will cycle between invoker and his 2 summons. It won't differentiate between each summon and both will be selected. 
If i remember correctly the next unit hotkey used to select each unit individually regardless if they were the same type or not.

So in cases for heroes like NP,brood, invoker etc where you have a control just of the same summon unit (e.g. a control group of treants) - it won't cycle within each unit in the group. it will just go straight to the next control group.

**Comment by Akz77** [comment]
thank you very much. im not sure if any of the recent changes in the patch inaverdently changed this for me (there was a previous bug this patch where the take all stash items hotkey was broken - this is now fixed).

will set to false and revert back if that does what is intended

**Comment by Akz77** [comment]
yep setting to false works as how i intended it. I could've sworn they made this an option in the UI (rather than via console) - perhaps my bad memory.

**Comment by Aluerie** [comment]
eh well then, since there is no bug in here then you should probably close this issue ; 

---

You can open new issue with QoL request to add `dota_selection_group` console command functionality into settings UI and suggestion to make extra keybind to toggle the value (currently you can do that with console `bindtoggle`).

But idk, it's like one of things that interested nerds will find anyway and not interested people won't think about.

**Comment by Akz77** [comment]
Closed - thanks mate for the help.
