### ISSUE TITLE
DPC Player Packs disappear after restart

### ISSUE THREAD

**Issue by Zomv1** [ValveSoftware/Dota2-Gameplay#7486]
### Item name

DPC Player Packs

### Description

Yesterday  I bought Team Spirit Gold Tier Support and obtained 20 packs + 10 packs that were given for free due to a new DPC season. I haven't opened any that day, but now I have 0 packs. Furthermore, today I claimed one pack for the 1st win of the day and it disappeared too. 

### Example Match ID and Timestamp

-

**Comment by Zomv1** [comment]
![image](https://user-images.githubusercontent.com/50305192/224510889-300654e8-9a30-4d21-aa3c-26ac1eaac6d3.png)
![image](https://user-images.githubusercontent.com/50305192/224510901-f6ce1c86-41cf-4a46-9d0d-31199897652b.png)
![image](https://user-images.githubusercontent.com/50305192/224510913-9e516ee3-5cba-4f5a-8df9-2c2c8b66aadd.png)
![image](https://user-images.githubusercontent.com/50305192/224510931-4a536a63-25c3-4a64-853b-3395552d2711.png)

**Comment by commentator24** [comment]
#7454 please thumbs up and close duplicate issue

**Comment by xjjepx** [comment]
Item name
DPC Player Packs

Description
Yesterday I bought Team 10 packs that were given for free due to a new DPC season. I haven't opened any that day, but now I have 0 packs. Furthermore, today I claimed one pack for the 1st win of the day and it disappeared too.

ID JJEPgodota2.com

![Captura de pantalla (1)](https://user-images.githubusercontent.com/127640960/224521779-c20af63b-2126-4c82-b51c-e5faeb078c67.png)
![Captura de pantalla (2)](https://user-images.githubusercontent.com/127640960/224521797-604e3b02-43a5-4d1b-b2ee-f1c843e12988.png)
