### ISSUE TITLE
Customer support gifted me 10 packs of player cards

### ISSUE THREAD

**Issue by hondacbr600** [ValveSoftware/Dota2-Gameplay#7554]
### Description

That's the default amount we get every DPC season. The issue is I received them today, meanwhile week 1 is on the go, so the roster is locked.

**Comment by Rodriz65** [comment]
It's great to hear that you received 10 packs of player cards from customer support. It's always a good sign when companies go above and beyond to make sure their customers are happy with their products or services. Enjoy your cards!

**Comment by commentator24** [comment]
yes it's great that they fix it. you're not really missing out much either. only 350 / 700 / 1050 / 1750 shards since region rewards don't stack. i put a few brown cards and at least got 350 lol
![image](https://user-images.githubusercontent.com/109324155/224960002-2fddcd1e-b06b-4ab6-929c-a5075afe132a.png)

hopefully someday they make more complex rewards like 350 for a complete team 5 brown card... or more shards for silver / gold.

**Comment by shaileshgarg** [comment]
Please close this issue.

**Comment by shaileshgarg** [comment]
Looks like the devs also gave 2 Fantasy levels as compensation.
