### ISSUE TITLE
muerta chest bug

### ISSUE THREAD

**Issue by adept25rus** [ValveSoftware/Dota2-Gameplay#7589]
### Description

Hello, I lost the already received items from the chest, I bought two keys, started to open the chest, but the items of the first tier that I had already received began to fall out again. Can you fix this somehow or refund my money? i bought keys to get pudg
![Снимок экрана 2023-03-16 в 17 10 54](https://user-images.githubusercontent.com/128061160/225647614-37c09211-890d-43d4-bcda-4a8df0c6985e.png)
a, but due to a bug now it is not possible. I re-dropped a set on Phantom lancer, and all the chests that I open next will be with tier 1 items that have already been obtained. The screenshot shows that I already have a Windranger set, but it is marked as not received.

### Screenshots

![Снимок экрана 2023-03-16 в 17 10 54](https://user-images.githubusercontent.com/128061160/225647865-15e2e820-ad17-4932-b20f-b2a23344fb92.png)

**Comment by Aluerie** [comment]
it's just how it works... 

tier 2+ are somewhat comparable to "rare" from usual treasures. You are lucky if you get those instead of tier1 in a roll. 

---

And I'm somewhat confident that it is how it *supposed* to be because otherwise Trade system five tier 1 for one tier 2 would be pointless if you could just exhaust-farm them out. 

--- 

So if it's not a bug - then, please, close your issue.

**Comment by adept25rus** [comment]
> 


it's sad that it works like that, I just lost 5$ trying to get pudge^ but...
