### ISSUE TITLE
Dota 2 SFM Bug with characters hair and belt

### ISSUE THREAD

**Issue by arminb98** [ValveSoftware/Dota2-Gameplay#7597]
### Description

there is a bug with SFM in Dota 2 Workshop tools .When I move characters that have hair and belts, They will stretch, Like their hair and belt doesn't move with body.

### Screenshots

![Screenshot 2023-03-17 133707](https://user-images.githubusercontent.com/15706440/225875397-0b5c22fb-09dd-45b9-aeaa-7299a3e52ebe.png)

**Comment by shaileshgarg** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/7551

**Comment by mpunishm** [comment]
I have same problem

**Comment by mpunishm** [comment]
I found how to fix this issue

just remove the lock from all of "dame_hair" parts and then you have no problem with it!
<img width="280" alt="Screenshot 2023-03-19 001103" src="https://user-images.githubusercontent.com/122637849/226138259-31f2e2ff-268a-44c2-909b-a7907024c0ff.png">

**Comment by mpunishm** [comment]
<img width="523" alt="Screenshot 2023-03-19 001340" src="https://user-images.githubusercontent.com/122637849/226138501-0600d871-227c-48a1-b91d-cef046534b5a.png">
<img width="572" alt="Screenshot 2023-03-19 001357" src="https://user-images.githubusercontent.com/122637849/226138502-b8078a57-11ce-4e41-a4f3-cc9e21d6bcac.png">

**Comment by videogameplayer909** [comment]
Does that issue fix the physics? How would unlocking the transforms affect the overall IK rig properties? Because with this 'fix', all my current pre-made dmx files are still affected by the transform issue. Also, having to look for every single affected bones for each hero is just not an acceptable solution.

Really hope Valve puts out a fix that addresses it for all heroes by default, instead of having to do manual selection and checkup

**Comment by shaileshgarg** [comment]
This was fixed in todays update.
