### ISSUE TITLE
BAG Will-O-Wisp BAG

### ISSUE THREAD

**Issue by YuioiuY** [ValveSoftware/Dota2-Gameplay#8014]
### Description

Good afternoon. I played on Keeper of the Light, noticed a bug when I bought an scepter and pressed Will-O-Wisp, the enemy characters could attack while in a dream!!!! and they got rid of him in a second. Did I just miss the patch or is it a feature? I'm sorry, but I lost because of this, and I framed my friends. Previously, characters could not attack under the Will-O-Wisp flash.

**Comment by TheUnholyWrath** [comment]
[Scepter Rework: Now gains Will-O-Wisp, however instead of a stun on flicker, it applies a movement manipulation that pulls units inwards at a rate of 60 units per second but does not prevent attacking/casting. Cooldown: 60](https://www.dota2.com/mistwoods)

When Kotl was reworked in 7.28 it was changed from a stun to a pull. Please close this issue.
