### ISSUE TITLE
Black King Bar + Halberd interaction is inconsistent

### ISSUE THREAD

**Issue by narvoxx** [ValveSoftware/Dota2-Gameplay#8376]
### Item name

Black King Bar

### Description

Currently, Black King Bar is interacting inconsistently with Halberd's Disarm debuff.
Take these two scenarios:
1) Try to Disarm a target with Halberd before they use BKB, then the target uses BKB
2) Try to Disarm a target with Halberd after they use BKB

(for context) Before the patch
Situation 1: the target can bkb, but the disarm debuff is not removed. Target is disarmed while BKB is active.
Situation 2: you cannot use Halberd on a target under the effects of BKB, target is not disarmed.

ACTUAL BUG (after 7.33):
Situation 1:  the target can bkb, but the disarm debuff is not removed. Target is disarmed while BKB is active (even though BKB provides debuff immunity, and halberd doesn't mention it pierces debuff immunity)
Situation 2: you CAN halberd a target that is affected by BKB, BUT the target is NOT DISARMED even though they will have the Disarm debuff.

In both situations, the target will be in a state of being affected by both BKB immunity and Halberd disarm at the same time, but in one situation they can attack and in the other they cannot. This is inconsistent. Either applying Halberd Disarm to a BKB'd target should disarm them, or one should be able to use BKB to supress the disarm. (probably the latter for balance reasons, but that isn't my call)

### Example Match ID and Timestamp

tested in custom lobby

**Comment by JoelMahon** [comment]
Not much to add other than I also noticed. Here is a reddit post with 1 minute video showcasing how it should work if not bugged  and doesn't pierce debuff immunity (like arcane curse with undispellable talent) vs how it does work as of right now.

https://new.reddit.com/r/DotA2/comments/13ghlc5/halberd_is_currently_bugged/

If it is supposed to pierce debuff immunity
1. Say so on the item
3. It should apply on a target if halberd is used during an on going BKB

**Comment by mastercoms** [comment]
This was changed in 7.34 as a balance update seemingly. "Disarm no longer pierces debuff immunity if applied beforehand". Personally, I feel like this is a bit of a misnomer since originally this was not made as a pierce to immunity, but rather, this is an interaction with dispells. The original change in 7.06 was "Heaven's Halberd can no longer be dispelled by spell immunity." This was an intentional balance change to prevent BKB being an answer to disarms that were applied in a timely fashion before a carry activated their BKB. The tradeoff was to preemptively activate BKB earlier in order to avoid disarms. In fact, I believe this change directly addressed a balance issue with Slark iirc at the time.

**Comment by narvoxx** [comment]
Was addressed in patch as mentioned by mastercoms. BKB now supresses Halberd disarm.
