### ISSUE TITLE
Alt ping (Standard ping) doesn't work as intended

### ISSUE THREAD

**Issue by nevinm** [ValveSoftware/Dota2-Gameplay#8551]
### Description

Even after customizing the ping wheel and switching it and reverting back to the original settings, the primary ping doesn't show a rune/building/item on the floor. This can be annoying for game play. I have added a video for reference. Also attaching the screenshot of my configuration for the ping wheel.

One clue here is even if I switch the main "Standard ping" to attack/ward etc.. that doesn't switch. That could be the key  to the solution.

### Example Match ID (and possibly Timestamp)

None

### Screenshots

https://user-images.githubusercontent.com/5534190/234044114-5d216af3-6348-47f9-ab5a-c8cc2fdf8978.mp4

![ping settings](https://user-images.githubusercontent.com/5534190/234044603-b192ffda-e951-4167-b0e5-68d3037fbdaf.jpg)

**Comment by nevinm** [comment]
Bump

**Comment by nevin-mk** [comment]
dota_ping_menu_delay 0.15 fixed the issue. Apparently it was set around 0.00100

**Comment by nevinm** [comment]
dota_ping_menu_delay 0.15 fixed the issue. Apparently it was set around 0.00100

**Comment by CommunistMountain** [comment]
Hi nevinm, I think this issue should be reopened. This is because setting the delay to a higher number is just a bandaid solution, if the delay is set to 0, this issue still persists. It is particularly important because you cannot ping runes. The exclamation mark ping in the ping wheel should behave identically to the normal exclamation mark ping.

If you do not want to reopen this issue, I shall make an identical one.
