### ISSUE TITLE
Io + Primal Beast can Move Tormentor to Fountain, which results in Fountain Killing Itself

### ISSUE THREAD

**Issue by Flam3sDOTA** [ValveSoftware/Dota2-Gameplay#8679]
### Description

Io + Primal beast moves Tormentor to base, Fountain attacks the Tormentor and kills itself which results in no regeneration, and no courier invulnerability aura.

**[Video](https://www.youtube.com/watch?v=hKvw6QjvAgM)**

### Match ID (and possibly Timestamp)

7126477766 - 20:22

**Comment by Singularity-** [comment]
Hello indeed : same here 7126907572

Give me my MMR back :DDD

**Comment by nathank-valve** [comment]
This will be fixed in a hotfix later today. Closing

**Comment by AHollowedHunter** [comment]
Will people abusing this be punished? Just had this in a ranked game 7126951829

**Comment by AHollowedHunter** [comment]
Will people abusing this be punished? Just had this in a ranked game 7126951829 @nathank-valve

**Comment by SnEkit** [comment]
People are abusing this in ranked. Just had a fontain kill in here  : 
![image](https://user-images.githubusercontent.com/131920774/234710200-894ae0d6-217c-41f1-9789-fabe2726852c.png)

**Comment by Ofek-Elgozi** [comment]
Same here. Tormentor spawn in my base, and since then fountain crashed.. no regen and enemy could go up easily.
Name in game: Buba
Match: 7127061788
Minute 22:30 ~
Can i get my MMR back please? it was insanely weird.
![2](https://user-images.githubusercontent.com/73593989/234729910-423e9d4a-848d-41ea-9ed3-9e78015b9f49.png)
