### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by asfafshjafshgj** [ValveSoftware/Dota2-Gameplay#8700]
fixed

**Comment by cyrusforoughi** [comment]
I have my own post (#8686) that has a somewhat similar story. Went 17-2 and lost 600MMR (Immortal down to Divine 3). I hope there is some fix/adjustment.

**Comment by AnanasSok** [comment]
When I see posts with the title "lost 500 MMR", it makes me a bit amused. On the other hand, going from 9000 to 8500 is more serious than from 4000 to 3500. But the problem here is on a larger scale, going from 9000 to 5000. Perhaps Glicko reacts too strongly to a prolonged break from the game (given your level of play). I hope they can help you, or share the formula for calculating the rating. But unfortunately, it seems to me that this is the new reality and we'll have to accept it.

**Comment by cyrusforoughi** [comment]
Why would you be amused? Valve just applied one MMR fix that impacted ~1% of accounts so its still being evaluated/updated. It is important for people to post possible issues/bugs so that they can be evaluated. If someone wins a bunch of games and loses MMR, it makes sense to make sure something isn't broken.

**Comment by asfafshjafshgj** [comment]
Its now fixed after night fix i'm playing my normal averages games now think i'm going back yo my previous mmr or mby more...

![image](https://user-images.githubusercontent.com/131480236/234939649-995d0b91-6b94-4799-9bee-cd3210db057a.png)

You can close it thanks

**Comment by AnanasSok** [comment]
> Why would you be amused? Valve just applied one MMR fix that impacted ~1% of accounts so its still being evaluated/updated. It is important for people to post possible issues/bugs so that they can be evaluated. If someone wins a bunch of games and loses MMR, it makes sense to make sure something isn't broken.

Yes, but everyone has just gone through a forced recalibration. In my opinion, losing 500 MMR doesn't affect anything.

**Comment by Aluerie** [comment]
> delete
> fixed

Just press "Close" button which is near "Comment" instead of editing/removing the content. :c 
![image](https://user-images.githubusercontent.com/33165440/235947400-437d1cbe-4628-47ea-a468-62cfb0a2f407.png)
