### ISSUE TITLE
Hoodwink Bushwhack cancels channeling BKB abilities

### ISSUE THREAD

**Issue by MaximProbst** [ValveSoftware/Dota2-Gameplay#8765]
### Ability name

Bushwhack 

### Description

Hoodwinks Bushwhack cancels channeled Abilities while the user has an active BKB.
For example:
Enigma uses Blackhole with active BKB and close to a tree.
Hoodwinks Bushwhack will cancel Blackhole, while Enigma neither gets stunned, nor moved towards the tree.
Can be recreated in a Test-Lobby.

Match example is an Ability-Draft game with Shadowdemon using shard-mana-drain and getting canceled by Lifestealer useing Bushwhack.

### Example Match ID (and possibly Timestamp)

7124679854 - 34:50

**Comment by anotherCoward** [comment]
Lions shard effect is not the same effect as a BKB. It just looks similar. It is known to act differently to BKB. Same applies to Dawn Breakers shard effect and Legion Commanders Level 25 Talent. 

See also https://www.reddit.com/r/DotA2/comments/qgnyp4/suggestion_fix_lions_shard_to_apply_basic_dispel/

**Comment by MaximProbst** [comment]
not the point tho, BKBed blackhole is still getting interrupted by bushwhack and spear. This has nothing to to with the disspell part of bkb. I think its because of the forced movement-component of bushwhack and spear.

**Comment by anotherCoward** [comment]
@MaximProbst

- Magnus Skewer won't cancel it (doesn't move Lion at all)
- Basher (noted in extended tooltip) requires a strong dispel too and therefor cancels the channeling.
- Abyssal Blade (Pierces Immunity) cancels it (autohit + active)
- Wind Lace or Eul's Scepter won't cancel it.
- Nullifier (Basic Dispel) won't disable it.

It is just soft debuff immunity. Everything that is piercing or strong will take effect against lion.

**Comment by MaximProbst** [comment]
I dont think you understand wht requires a string defbuff is. Abilities that can only be removed by strong defuffs are ussally stuns. This does not apply to the application of stuns. An ability can either pierce debuff immunity or not. CK stun for example can only be removed by strong dispells and cannot pierce debuff immunity.  -> abaddon shield removes the stun, and sthe stun doesnt pierce bkb

**Comment by anotherCoward** [comment]
Well: "It is unclear if Bushwhack is piercing or not." -- That info is missing on the ability tooltip for Bushwhack. It also works fully on BKB not just Lions Debuff Immunity. The Wiki's are (for most of the spell immune stuff) outdated but a lot of useful infos are still there.

Anyway it's also true and false for [Spear of Mars](https://dota2.fandom.com/wiki/Mars#Abilities): at the same time.
> ```none
> Buff/Debuff                                        Modifiers
> modifier_projectile_vision                         Undispellable
> modifier_special_mars_spear_burning_trail_thinker  Unknown
> modifier_mars_spear_impale                         Death (moment of impact on the first target)
> modifier_mars_spear_stun                           Strong
> modifier_knockback                                 Basic (that's why bkb'd target isn't moved)
> modifier_special_mars_spear_burning_trail_burn     Basic
> ```

Every effect of the spear has different dispel types and the impale effect (moment of impact) is stronger than the debuff imunity from BKB. That's why the black hole gets canceled but the unit isn't moved. But Lion is moved, because the impale effect cancels the debuff imunity effect.

Bushwhack also has multiple effects that can apply (the vision, the damage over time and the stun are different effects) and one of them must have [Death dispel type](https://dota2.fandom.com/wiki/Dispel#Death), otherwise it wouldn't bypass the BKB either.

**Comment by EthanChoi-quark** [comment]
Still an issue, same with Mars Spear

https://user-images.githubusercontent.com/67212338/235824047-928b5d21-3c5b-49f8-b479-983723c0d906.mp4

**Comment by Aluerie** [comment]
Fixed pls close ![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/c81462d5-8c7c-45fa-8882-070a55dfc90b)
