### ISSUE TITLE
Zeus aghs shard stopped working

### ISSUE THREAD

**Issue by artillicime** [ValveSoftware/Dota2-Gameplay#9117]
### Ability name

Zeus lightning hands

### Description

The shard stopped working and didnt apply an arc lightning on hit for some reason. I don't see an apparent reason...

### Example Match ID (and possibly Timestamp)

7148329252 - 33:57

**Comment by commentator24** [comment]
im guessing just like other bug reports like #8541 you didnt realise you turned off autocast until the rest of the game hence it no longer works

**Comment by artillicime** [comment]
Why in hell would I want such an option?? But if it is the case I had many issues with acorn shot in the past disabling auto-cast by itself. Like many time in the game screwing my tree planting!

**Comment by commentator24** [comment]
the option still can be useful in some situations. 
e.g. you got shard from tormentor and vs axe and LC. you didnt really want it.
keep dying because of blink taunt blademail + your auto arc. (open bug issue if theres no option to turn it off?? 😆 ) you turned it off during duel or axe taunt, and it no longer cast as you attack so you survived.

anyway you should close the issue if forgetting autocast is the case 😄

**Comment by artillicime** [comment]
I still have an issue with auto-cast removing it status by itself if you read fully the comment... although it seems weird that while taunted you could disactivate it ....

**Comment by artillicime** [comment]
*** So this is the why, but I want to talk about the how!? Especially if it is the case with so many other players and abilities in the game. Shouldn't be that great they find a fix for all these unknown issues!? I've tried to watch the replay in player view to find out if I can find a clue about it. But the game crash just before that moment every time... :-/
