### ISSUE TITLE
Silencer does not steal 5 int when holding aghanim shard

### ISSUE THREAD

**Issue by Wolfgangs246** [ValveSoftware/Dota2-Gameplay#9210]
### Item name

Aghanim Shard

### Description

Silencer does not steal +5 Int when holding the aghanim shard. 

### Example Match ID and Timestamp

Match 7151036018

**Comment by commentator24** [comment]
you mean the right click attacks? you wont get 5 int steal for attacking naga siren illusions.
Glaive attack counter is for silence. you probably saw it wrong cos i watched the replay a bit and both working properly. I think i saw you get 5 int from 123 to 128 dmg. after that you just kept dying and had no chance to right click.

probably easier if you tell the time it happened, otherwise you can close the issue.

**Comment by Wolfgangs246** [comment]
Sorry I made a mistake. For the longest time I read the skill text to mean that with a Shard and max 2nd Skill, I should be stealing +5 int if a enemy hero dies in my vicinity. After rereading, I recognize my mistake. I'm stealing +5 int with every hit. the perm int steal is only +2 and +4 with shard.
