### ISSUE TITLE
spirit breaker bug

### ISSUE THREAD

**Issue by kirsoms** [ValveSoftware/Dota2-Gameplay#9218]
### Ability name

charge of darkness

### Description

the first ability was bugged and could no longer be used. ability was always on cooldown

### Example Match ID (and possibly Timestamp)

7155411406 21:15

**Comment by Experiment626s** [comment]
#9242

**Comment by TheUnholyWrath** [comment]
This issue is related to #2984. Normally when Spirit Breaker dies to Ice Blast, he will continue charging even after he dies and hit the target, and his charge CD is properly reset. In both this game and #9242, Spirit Breaker charges a creep that dies before he can complete the charge, so charge never gets properly reset.

**Comment by Nathanael-Valve** [comment]
Should be fixed next update.

**Comment by TheUnholyWrath** [comment]
#9589 This bug can still be replicated, this should probably be reopened.
