### ISSUE TITLE
Bane loses its nightmare ability after dying under nightmare

### ISSUE THREAD

**Issue by diomari** [ValveSoftware/Dota2-Gameplay#9348]
### Ability name

Nightmare

### Description

After dying under self targeted `nightmare` the skill changed to `nightmare end` for the rest of the game.

### Example Match ID (and possibly Timestamp)

7164449617 - 26:50

**Comment by TheUnholyWrath** [comment]
#8883. Bane procs Phylactery with Nightmare on Spectre Illusion, killing it.

**Comment by diomari** [comment]
@TheUnholyWrath sorry forgot to double check with similar issue. On closer inspection bane tried to skill enfeeble and the phylactery worked but the skill enfeeble did not cooldown. But `nightmare` should not be in `nightmare end` state already since I was able to skill after hero was attacked.

I posted the vid here on reddit: https://www.reddit.com/r/DotA2/comments/13nqxee/nightmare_bug_on_bane_elemental/

**Comment by TheUnholyWrath** [comment]
Sorry I didn't explain anything. #8883 has 2 ways of reproducing this bug, the one that happened to you is [this one](https://github.com/ValveSoftware/Dota2-Gameplay/issues/8883#issuecomment-1529781374) or the 2nd video from the first comment. The bug happens when an enemy attacks a Nightmared unit and Bane kills them with a Phylactery proc from the Nightmare switch. In your case it was a Spectre Illusion that was killed. You're welcome to comment all of your information in #8883 or leave this issue open, just remember to come back and close it when the bug is fixed please. Thank you

**Comment by diomari** [comment]
This has been fixed on recent updates so closing this now.

**Comment by AramilRey** [comment]
This just happened to me on a ranked game, lost the ability for the remainder of the game, match id: 7609775630
