### ISSUE TITLE
Phylactery killing low health targets causing spells to not apply properly

### ISSUE THREAD

**Issue by TheUnholyWrath** [ValveSoftware/Dota2-Gameplay#9499]
### Description

The patch today fixed some spell interactions with Phylactery, here's some more

- [x] **Acorn Shot** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/e1d60faf-b3f6-4553-a7a9-16d248919a19

- [x] **Culling Blade**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/668386cf-dce3-4ebe-98c9-6bb1130ac19b

- [x] **Wrath of Nature** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/171edfb2-f2be-4db2-b1d6-e47fc1459936

- [x] **Sprout**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/8b7e005d-4905-4711-8df1-6bb988917398

- [x] **Splinter Blast** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/9459a6c0-f1b2-4bbe-9010-db80155b4a3b

- [x] **Fatal Bonds**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/4d143706-f8a8-47e6-a950-940d14906618

- [x] **Fade Bolt**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/f5cee270-243a-4309-b467-8d9e718f9429

- [x] **Thunder Strike**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/9363a7bd-c219-4974-b590-877bde7c1962

- [x] **Dead Shot** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/ada4e32f-bd2e-4aaa-b39d-41aca9b4e4b1

- [x] **Poison Touch**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/363bd798-043d-4ea0-8e52-f0138fe96ca5

- [x] **Tar Bomb**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/ed5f1fd7-2660-4b7e-85d0-44f1edbb9c3f

- [x]  **Magic Missile**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/0637f155-4d3d-40a7-ba3b-822fca057901

- [x]  **Shackleshot**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/58920e63-db07-47ff-908e-1f9261ca677b

- [x] **Lightning Bolt** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/640d8edd-f562-4c70-a5a7-9ade72eb5de4

- [x] **Lightning Storm** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/04ddc71c-5b33-4493-9107-3fcfe775e730

- [x] **Dragon Tail (with level 25 talent)**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/c738c719-93d1-4aca-92fc-3fa534fb459e

- [x] **Blink Strike** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/5ed378e7-fcfb-4a11-88e4-452bc1049cc2

- [x] **Mana Void** 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/67005914-470b-435d-b868-a56483a1a7be

- [x] **Sunder**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/ad165642-1953-405f-86b2-1510dd86b3fb

- [x] **Duel (permanent damage buff)**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/bff7d092-22fa-4a73-9fe0-135feaac33a5

- [x] **Finger of Death (permanent damage buff)**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/506b23a5-a010-49f1-92cb-5d3c94ffa5fb

- [x] **Reaper's Scythe (permanent buff)**

https://github.com/ValveSoftware/Dota2-Gameplay/assets/46859977/4852eea9-babd-4311-b416-0f950581fba3

**Comment by deanrih** [comment]
Reference to another already exists issue #9456 #9448 #9426 

Some of it kinda make sense like Blink Strike because the target dies before the ability can apply it's effect so you can't blink to a corpse, they either have to change the order or how the ability applying it's effect. Also for Culling Blade, Duel and Reaper's Scythe, since the target die first and died by the Phylactery instead of the ability, therefore no permanent ability bonus were given.

If you open Combat Log you can see everything happening in order, I think the more sensible fix is Phylactery should proc when an ability already done applying it's effect, even if the ability hasn't deal any damage yet.

**Comment by blessedmulligan** [comment]
>Also for Culling Blade, Duel and Reaper's Scythe, since the target die first and died by the Phylactery instead of the ability, therefore no permanent ability bonus were given.

I think before this patch, phylactery didn't cancel these (at least culling blade, which I remember specifically testing). I think, jank aside, that's how it should work. the tooltip reads "The next single target spell you cast on an enemy deals a separate 150 bonus damage." Key phrasing here being that the *spell* does the damage, not the item (although who knows how it's actually implemented). Personally, I think that either the abilities shouldn't be cast at all, or if they do go on cooldown, at least grant their effects.

This would be consistent with how Last Word works: If someone tries to cast a spell while last-worded but is killed by the damage, the skill neither has any effect nor triggers the cooldown (although cast triggers like wand, aftershock, etc still trigger)

**Comment by deanrih** [comment]
@blessedmulligan I think it's because Phylactery only applies damage when an ability "lands" on the target, so at that point, Culling blade is already "landing" or "hitting" the target, but Phylactery deals damage just after that happened and before Culling blade applying its damage and effect, so the ability is already on cooldown, but the enemy is already dead by the Phylactery damage, when the Culling blade tries to apply its damage and effect, the target is already dead, so it doesn't process it, I guess. I think they should fix that if a unit dies within this Culling blade ability window (starts when the ability "lands"/"hit"), it still counts as Culling blade's kill and give the permanent bonus, and should be applied to with any ability to be fair, so Reaper's Scythe and Duel will get the fix too

**Comment by cadaeic** [comment]
Allowing Phylactery to take effect after a momentary delay (like Dagon does) would pretty much prevent this kind of race condition for good. It would also allow Phylactery to stay on cooldown if the target is killed rather than going to waste -- although I guess that would be a significant buff for an already popular item.

**Comment by TheUnholyWrath** [comment]
All of these interactions have been fixed. Closing

**Comment by Aluerie** [comment]
Idk if it's new or old or if it caused by recent https://github.com/ValveSoftware/Dota2-Gameplay/issues/9589#issuecomment-1589874536, if it's a new issue material or devs will check this thread back for new stuff. 

Nevertheless, here it is: 

Spirit Breaker is supposed to change targets like this: 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/0693ac24-7e14-4a62-a6e1-86aa8c20c83a)

But in the next clip he will charge instead closest to his own location. 

https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/99dc09d2-a226-4b42-ae0d-a081cbddd22d

**Comment by TheUnholyWrath** [comment]
> Idk if it's new or old or if it caused by recent [#9589 (comment)](https://github.com/ValveSoftware/Dota2-Gameplay/issues/9589#issuecomment-1589874536), if it's a new issue material or devs will check this thread back for new stuff.

It was working somewhat like this but maybe not exactly before Phylactery broke with everything. Couldn't test it properly back then, but I'd charge something seemingly random across the map instead of anything close to where I was trying to charge. Testing it in lobby now it seems to pick something near you instead of near where you were trying to charge. I don't think its related to the rest of this issue (Spirit Breakers interaction with this issue was Charge not redirecting at all), you'd probably be better off creating a new issue for this.

**Comment by Aluerie** [comment]
well, here it is #9724
