### ISSUE TITLE
Black king bar doesn't block pure damage

### ISSUE THREAD

**Issue by DelusionalLogic** [ValveSoftware/Dota2-Gameplay#9585]
### Item name

Black King Bar

### Description

Black king bar states that the active ability Avatar:

    Applies a Basic Dispel. Grants 50% Magic resistance and immunity to pure and reflected damage.

But it doesn't seem to actually block ANY pure damage. It's also quite difficult to parse if it's supposed to block 50% or 100%. It's most easily testable in demo hero mode with Pudge hook.

### Example Match ID and Timestamp

7187769224 - 45:53

**Comment by commentator24** [comment]
i think you don't fully understand how bkb works because you mentioned demo hero with pudge hook.
if magic, pierce or not, you block 50% dmg. e.g. void spirit ult.
if pure + pierce bkb you will block 0%. e.g. pudge hook pierce so 100% dmg. 
if pure + not pierce bkb you will block 100%. e.g. tinker laser, so 0% dmg.
if physical, well physical is not magic or pure so pierce or not, 100% dmg + resist based on your armor.

the only bug is probably any tooltip of physical spell e.g. sladar crush / tide anchor / MK stun because even if says doesn't pierce it still pierce (useless tooltip?). all physical spells basically pierce bkb now i think.

i didn't watch the replay so im not sure if theres something more, otherwise you can close this issue

**Comment by Aluerie** [comment]
> if magic, pierce or not, you block 50% dmg. e.g. void spirit ult.

wrong as i replied in your skymage post. 

> sladar crush / tide anchor / MK stun

Pierce line is about debuffs those spells do.

**Comment by commentator24** [comment]
guess i didnt fully understand it too hehe

**Comment by DelusionalLogic** [comment]
Ah, so "piercing immunity" also means it pieces this new pure damage immunity. That wasn't clear to me but seems consistent with my observations. Closing issue.
